### ISSUE TITLE
Toa change crash

### ISSUE THREAD

**Issue by ShadowOfNight** [TheLegendOfMataNui/game-issues#10]
Switching to Onua or Gali (if not Gali already) in Gali's level causes the player to spawn outside of the map and fall to death.  In almost every area I tested, this caused a crash.  Warping to VLGS and changing toa causes the player to spawn outside the map and enter a death loop.  Did not crash here though.

**Comment by ShadowOfNight** [comment]
In BKIK in Pohatu's level, changing toa causes a spawn outside of the map, the deathfall loop, and ultimately a crash.

**Comment by ShadowOfNight** [comment]
This is still a problem in some areas of the beta.

**Comment by Vahkiti** [comment]
@ShadowOfNight This is fixed now, yes?

**Comment by ShadowOfNight** [comment]
Yeah.  The alpha probably still has the problem but I don't see a need to correct that considering some of the code that causes it I _believe_ might still be used.  For our purposes this is fixed yes, and therefore I'm closing it.
