### ISSUE TITLE
Lewa's level lacks a boss door

### ISSUE THREAD

**Issue by robot5431** [TheLegendOfMataNui/game-issues#105]

**Comment by robot5431** [comment]
My guess is that it would be here, as it leads to a large room that is a one-way trip and that room leads into the boss room.
![bandicam 2018-04-01 08-47-07-636](https://user-images.githubusercontent.com/37253627/38173807-76548908-3589-11e8-941c-4bd674da44d9.jpg)

**Comment by ShadowOfNight** [comment]
The beta does in fact have a boss door now, so this issue is being closed.

**Comment by ReeseWB-001** [comment]
Closing this issue since, judging by how we now know Gali's shrine works in the alpha, this level was not meant to have a token-based boss door.
