### ISSUE TITLE
GLY3 in Lewa's level lacks slide physics

### ISSUE THREAD

**Issue by robot5431** [TheLegendOfMataNui/game-issues#106]
For example, 90% of the level has no walls. If you're careful to avoid invisible death plains, you can almost fall from the beginning straight to the end.

Video example: https://youtu.be/L8ReT15oxbg

**Comment by PeabodySam** [comment]
I actually suspect that the lack of walls is deliberate. The layout reminds me of the slide levels from Super Mario 64, and so falling off into the abyss and dying would be the penalty for failing to stay on the course. I wonder if GLY3 might have been intended to be played like the surfing levels of Gali, Kopaka, and Tahu's levels (maybe Lewa would've been tree-surfing like Disney's Tarzan?).

The lack of textures, on the other hand, definitely needs help.

**Comment by robot5431** [comment]
That would make sense. I think BIONICLE: The Game had sections like that, so I wouldn't be surprised if it would be here as well. It being an elevated section (much like the room where you get the shield glyph) would suggest that it could be up in the trees.
Oddly, the other sliding sections are programmed in already, so I wonder why they wouldn't have already programmed it in if this was the case.

**Comment by ShadowOfNight** [comment]
@PeabodySam @robot5431 

GLY3 actually does have textures.  Turn on the Ruru to see this.  
I suspect this area might have been intended as a mine cart ride.  Considering this is a dark area (hence why the Ruru reveals textures) it makes me think this is supposed to be a mine.

**Comment by robot5431** [comment]
@ShadowOfNight I noticed the textures while I was testing the hover animation bug ( #107 ). I also agree with the explanation as to why the textures are hidden by the Ruru (being in a cave). 
However, I find it odd that it would be a minecart section. For all the time up in the trees this level has, it would be jarring to have a random minecart ride. If anything, that would be in Onua's level.
I agree that it would be a section akin to that, but I'm not so sure what it would have been.

**Comment by ShadowOfNight** [comment]
Turns out this area actually was a slide and was finished.  The point remains to be seen since the glyph was removed from this room... 

Closing this issue.

**Comment by ShadowOfNight** [comment]
The code to actually enable the slide functionality was partially there but incomplete.  This has now been resolved and will be included in the next alpha patch release.  Closing ticket.
