### ISSUE TITLE
The palm trees in Gali's BECH/STRT have no collision data

### ISSUE THREAD

**Issue by robot5431** [TheLegendOfMataNui/game-issues#109]

**Comment by ShadowOfNight** [comment]
@robot5431 This has been known for as long as we've had the alpha.  Me and another user from Beaverhouse created a .bcl mesh for the area to fix this, but it apparently causes a conflict with the transparencies on that map.  An .ocl file for this area will need to be made eventually; I hope it somehow doesn't cause another conflict.

**Comment by ShadowOfNight** [comment]
Fixed in both builds of the game.
