### ISSUE TITLE
Collecting blue orbs shutdown

### ISSUE THREAD

**Issue by ShadowOfNight** [TheLegendOfMataNui/game-issues#11]
In Gali's level, collecting the blue orbs seen in TTUN and elsewhere causes the game to shutdown.

**Comment by 2Tie** [comment]
presumably these air bubbles should refresh the air timer before you get the kaukau, as other underwater tunnels simply have energy orbs.

**Comment by ShadowOfNight** [comment]
Yes, that's what I think.  Probably should have updated my first post with that.

**Comment by ShadowOfNight** [comment]
Resolved entirely in the beta; closing this issue.

**Comment by ShadowOfNight** [comment]
Fixed.  The game is missing a subroutine (replenishair) to tell it what to do once the toa in question (Gali) comes into contact with the air bubble.
