### ISSUE TITLE
Sometimes, jumping off of vines results in death 

### ISSUE THREAD

**Issue by OndrikB** [TheLegendOfMataNui/game-issues#112]
In Lewa's level (most apparent in le07), if you jump off a vine (or jump off a vine and instantly activate the Miru), Lewa dies. This might be a softlock, but I don't know.

**Comment by ShadowOfNight** [comment]
This issue is no longer a thing in the beta, so I'm closing this.

**Comment by OndrikB** [comment]
Issue still persists in the beta, but to a much lesser extent (Visible at 3:16:20 in the Beaverstream)
Also, it’s no longer a softlock.

**Comment by ShadowOfNight** [comment]
Reopening this issue as it appears to be a problem for the most part on Win8/10 in the beta.  Only seems to occur in the room LE03 but more investigation is needed.

**Comment by ReeseWB-001** [comment]
This issue has been fixed by adding a bcl under each offending map.
