### ISSUE TITLE
Gali's upgraded energy ball, when collected, displays a text error.

### ISSUE THREAD

**Issue by robot5431** [TheLegendOfMataNui/game-issues#113]
![bandicam 2018-04-13 20-12-37-229](https://user-images.githubusercontent.com/37253627/38762897-1751079c-3f57-11e8-84f5-6ef5dac91a64.jpg)

This is especially odd, as the other upgraded balls don't have any other text after the line:
"(Toa)'s energy ball is now even more powerful."

![bandicam 2018-04-13 20-16-31-911](https://user-images.githubusercontent.com/37253627/38762929-9e209e9a-3f57-11e8-8c7e-819f0a746d2d.jpg)

**Comment by ShadowOfNight** [comment]
No longer an issue in the beta so I am closing this.

**Comment by ShadowOfNight** [comment]
OSI was calling 3 strings for the text when there are only 2 for it to read, hence the XXX.  Issue resolved.
