### ISSUE TITLE
The Rahi in Kopaka's PATH don't animate properly upon seeing you

### ISSUE THREAD

**Issue by robot5431** [TheLegendOfMataNui/game-issues#114]
Video example: https://youtu.be/c91bR0FT1EY

**Comment by ShadowOfNight** [comment]
Still an issue in the beta.  I believe this is an AI issue because modifying the AIInfo.slb doesn't affect this at all.  Multiple other rahi suffer from the same problem.

**Comment by ShadowOfNight** [comment]
Because there is an issue dedicated to all broken Rahi AI, I'm closing this issue.
