### ISSUE TITLE
The Launcher isnt detecting the game

### ISSUE THREAD

**Issue by StrangeGirlFromAnotherStar** [TheLegendOfMataNui/game-issues#115]
Hi I was wondering if anyone knew how to fix the issue im having with the launcher as it it is not detecting the game, the game is installed on a flash drive if thats the problem any response will be great. 
Thanks - Mili

**Comment by Jelmer-ja** [comment]
IIRC the launcher only detects the game if you installed it in the same folder as you installed the launcher.
