### ISSUE TITLE
Onewa's conversation crashes (predominantly) on Windows 10.

### ISSUE THREAD

**Issue by ShadowOfNight** [TheLegendOfMataNui/game-issues#117]
This seems to be specifically an issue on Windows 10.

As soon as you press the spacebar to continue to the second part of the conversation in Onewa's hut, the game will crash.

**Comment by R3-T7** [comment]
I am having the same problem

**Comment by PeabodySam** [comment]
Confirmed to occur in Windows 7 as well.

**Comment by ShadowOfNight** [comment]
@PeabodySam This is the first report of this happening in Windows 7.  If you could obtain the crash address on your end, that would be appreciated.

**Comment by PeabodySam** [comment]
@ShadowOfNight It's surprisingly inconsistent. While it crashed as expected on my first try after seeing this thread (and tended to crash frequently during prior playthroughs), the conversation randomly decided to proceed normally for a few times while trying to get an answer for you. I swear, this game is coded with quantum physics!

Then, quite (un)fortunately, it finally crashed again on my third or fourth attempt. So, here's the crash address I got for you:

0044cb66

**Comment by ShadowOfNight** [comment]
The conversation has never crashed for me at all, but considering the state this game is in, the crashing doesn't surprise me.

**Comment by OndrikB** [comment]
It probably got fixed in update 1.1. Never crashed for me at all in it.

**Comment by ShadowOfNight** [comment]
This has not been a reported problem for quite some time, so I'm closing this issue for now.
