### ISSUE TITLE
Beta crashes and throws an exception in front of white screen with music upon launch

### ISSUE THREAD

**Issue by SilverDeoxys563** [TheLegendOfMataNui/game-issues#126]
On Windows 10, whenever I try to launch the beta with the patch applied, I get a white window that plays music, my cursor turns invisible, and almost immediately after the window appears, the exception window pops up. After blinding trying to navigate over and pressing OK with my invisible cursor, Windows reports that the window isn't responding and needs to close.

[Here is a screenshot of what the game looks like.](http://puu.sh/AltoG.png)

[Here is a screenshot of the event viewer.](http://puu.sh/AltSG.png)

[My computer's specs.](http://puu.sh/AluXA.png)

[And the video card.](http://puu.sh/Alv0F.png)

**Comment by Vahkiti** [comment]
This has recently been discovered to be most likely to be your antivirus flagging one or more files in the mods folder. Please make sure that's not happening, and the issue should be resolved.
