### ISSUE TITLE
Alpha Problem

### ISSUE THREAD

**Issue by ghost** [TheLegendOfMataNui/game-issues#129]
**Build Version:**

Either 0.006 Alpha

**Steps to Reproduce:**

I am running a system with 16gb of ram, an i7 6700k overclocked to 4.5.
Every time I try to run the game it tells me to "download the alpha" so I do, and it still doesn't launch!

**Comment by ReeseWB-001** [comment]
@ReadyRedRed Are you still having this problem?

**Comment by ghost** [comment]
Yes

**Comment by Vahkiti** [comment]
How about now? There have been a few launcher releases since this.

**Comment by ShadowOfNight** [comment]
The user who originally posted this issue has deleted their account, therefore I'm closing this issue.
