### ISSUE TITLE
The game crashes on exit

### ISSUE THREAD

**Issue by Nic5-Cyprus** [TheLegendOfMataNui/game-issues#130]
**Remember to add the following information:**

**Build Version:**

0.006 Alpha

**Steps to Reproduce:**

I use Windows 10. Every time you quit the game from the title screen a pop up window appears saying "Unhandled exception c0000005 on address 0057b84b" and then the game freezes

**Comment by ReeseWB-001** [comment]
This was known already as issue #17 .

**Comment by ShadowOfNight** [comment]
This is a known issue.  In the future, please refrain from opening a new issue until you have searched existing issues, both open and closed.
