### ISSUE TITLE
Kopaka's BRD3 is uncontrolably fast

### ISSUE THREAD

**Issue by ReeseWB-001** [TheLegendOfMataNui/game-issues#131]
This bug pertains to the Beta build of the game.

When playing Kopaka's third slide section (labelled internally as BRD3, positioned after the area with the Kanohi Akaku (VISN)), Kopaka moves extremely fast to the point where he is far too difficult to control. His other three boarding sections (SNBD, BRD2, and BRD4) do not have this problem.

**Comment by ShadowOfNight** [comment]
By editing the surfminspeed and surfmaxspeed values in the brd3 puzzle section of the osi, I was able to resolve this issue.
