### ISSUE TITLE
Uncompletable Quests [Legacy Beta]

### ISSUE THREAD

**Issue by ShadowOfNight** [TheLegendOfMataNui/game-issues#132]
Quests in the beta that cannot be completed should be posted here.

Gali's level:
Ga-Koro Gate Stone -- This quest has no matoran to ask for or accept it.
~~Throwing Disc -- The matoran who asks for it won't accept it.~~

Lewa's level:
Volo Lutu Launcher --  This quest has no matoran to ask for or accept it.

Tahu's level:
~~Throwing Disc -- The disc itself was not placed in an area.~~
Winch Lever --  This quest has no matoran to ask for or accept it.

NOTE: the Gear quest in Gali's level was uncompletable in the unmodded beta.

EDIT 1: Gali's level disc quest is now completable; the Tahu level disc can be collected, but is accepted by the wrong quest giver currently.

**Comment by OndrikB** [comment]
The disc was placed in TA14, but is unobtainable (it's just as if you'd enter the area with another character)

**Comment by spmoc045** [comment]
You can't even pick up the gate stone in hk01

**Comment by OndrikB** [comment]
The gate stone is not in HK01

**Comment by spmoc045** [comment]
Then what is it https://i.imgur.com/1TFWv8Z.jpg

**Comment by OndrikB** [comment]
that’s a part of the area iirc. The gate stone is in vllg

**Comment by Vahkiti** [comment]
Is this still an issue? I know it's not in REBUILT, but what about legacy?

**Comment by ShadowOfNight** [comment]
This has been addressed as far as broken quests are concerned.  Quests that cannot be completed due to quest givers not existing will not be fixed as that is outside the scope of Legacy Beta.  This is not an issue in Rebuilt.  The Lava Board and throwing disc in lev6 will be accepted by the correct quest givers in the next patch.  Closing ticket.
