### ISSUE TITLE
When playing in windowed mode, clicking out of the window unpauses the game

### ISSUE THREAD

**Issue by ReeseWB-001** [TheLegendOfMataNui/game-issues#133]
This issue is from the Beta version.
The pause text remains onscreen, but the HUD, the character, and everything else will move. Rahi can also attack and kill you during this time.

**Comment by ReeseWB-001** [comment]
Oddly, this doesn't happen if you don't pause the game first (though the cursor still spins).

**Comment by ReeseWB-001** [comment]
This was also not a problem in the alpha.

**Comment by Vahkiti** [comment]
Fixed as of REBUILT 1.1 and Beta 1.0.5.

**Comment by ShadowOfNight** [comment]
Reopened due to this being internally reverted, added back to In Progress

**Comment by ShadowOfNight** [comment]
Fixed in the next patch, closing for good
