### ISSUE TITLE
Toa is unable to move after playing second horn on Level 2 - Gali.

### ISSUE THREAD

**Issue by Expack3** [TheLegendOfMataNui/game-issues#135]
**Summary:**
When playing Gali from the developer level menu, attempting to play the second horn when trying to solve the lake puzzle causes the Toa to be unable to move.

**Build Version:**

"Beta" October 23, 2001

**Steps to Reproduce:**

1. Replace the dgVoodoo2 DLLs with the [latest stable](http://dege.freeweb.hu/dgVoodoo2/dgVoodoo2.html) (2.55 as of this posting)
2. Copy-paste the contents of dgVoodoo.conf with [this.](https://gist.github.com/Expack3/5964ed66ded09e1e0f3ee15475faaead)
3. Go to level 2 from the developer's menu.
4. Free the village.
5. Collect the grappling hook.
6. Collect the gate stone from atop the archway in the village.
7. Collect the Mask of Translation.
8. Get the missing throwing disc.

9. Use the Mask of Translation to read the writing on the lake wall.
10. Play the second horn using the Spacebar key.

**Comment by ReeseWB-001** [comment]
This is already an issue reported on this page, and applies to all of the horns. Please read all of the reported issues before posting a new one (Issue #123 )
