### ISSUE TITLE
Frontend menu cursor invisible on branching screens

### ISSUE THREAD

**Issue by Expack3** [TheLegendOfMataNui/game-issues#136]
**Summary:**
When running the game through the frontend, the mouse cursor is invisible except on non-branching screens, like the save game menu, the graphics menu, etc. This excludes the Controls menu, which appears to use the same logic as the branching screens (e.g. main frontend menu, main options menu, etc.)

**Build Version:**

"Beta" October 23, 2001

**Steps to Reproduce:**

1. Replace the dgVoodoo2 DLLs with the [latest stable](http://dege.freeweb.hu/dgVoodoo2/dgVoodoo2.html) (2.55 as of this posting)
2. Copy-paste the contents of dgVoodoo.conf with [this.](https://gist.github.com/Expack3/5964ed66ded09e1e0f3ee15475faaead)
3. Load the frontend.
4. Move the mouse. No cursor should be visible.
5. Press the Enter key to progress to the save game menu.
6. Wait for the save game menu to load.

7. The mouse cursor should now be visible.
8. Click on the "Back" button.
9. Wait for the main menu to load.
10. The cursor should no longer be visible.
11. Move the invisible cursor over the "Options" button. The button text will turn yellow and, if you have audio enabled, an audio effect will play once the mouse is over the button.
12. Wait for the main options screen to load.

13. There should still be no mouse cursor.
14. Click on any of the options except the controls or credits buttons. The same behavior as Step 11 applies.
15. You should see the mouse cursor once the menu has loaded.
16. Click the screen's "Back" button, or click the right mouse button if there is no button.
17. Wait for the main options menu to load.
18. Select, then click on either the controls or credits button.
19. Wait for the selected screen to load. The mouse cursor should not be visible.
20. Return to the main menu.
21. Select and click on the "Quit" button.

**Comment by ReeseWB-001** [comment]
Oddly, if you use the debug camera to move Onua's position in the Frontend map and get control of him, the cursor appears.

**Comment by OndrikB** [comment]
This was somehow fixed in patch 1.1 (at least on Windows 10)
