### ISSUE TITLE
I can't seem to get Onua's door open

### ISSUE THREAD

**Issue by Alconpoke** [TheLegendOfMataNui/game-issues#137]
"Beta" October 23, 2001

I don't know if this is me being stupid but I can't find a way through the door with Onua's mask next to it when first starting up the game. The door I'm talking about is at the bottom of the pit after jumping up the first set of steps.

Also I can't seem to find a list of instructions but I've pressed every button I can on the mask symbol and nothing seems to be working.

**Comment by ReeseWB-001** [comment]
Press Shift to activate the mask. Press up against the lighter part of the wall and attack.
