### ISSUE TITLE
Beating the Vatopa-Nui causes the dialogue after defeating the Kokuru-Nui to crash the game

### ISSUE THREAD

**Issue by ReeseWB-001** [TheLegendOfMataNui/game-issues#140]
Defeating the Vatopa-Nui and then defeating the Kokuru-Nui crashes the game after Nuju finishes speaking (at address: 00488e03). There is no clear reason that this happens, and it prevents the game from being completed in one proper runthrough.
This does not occur with any other level.

**Comment by ReeseWB-001** [comment]
After some testing, this occurs both from the debug menu and Front end.

**Comment by ReeseWB-001** [comment]
This issue seems to be tied to Pohatu's Makoki Stone, which causes a cleanup crash upon Nuju's convo ending (where the game is supposed to give you Kopaka's stone). Proven by dummying out the stone, which does not cause the crash to occur after beating both the Vatopa-Nui and Kokuru-Nui.

**Comment by ShadowOfNight** [comment]
Issue seems to have been fixed by restoring functionality to the resetdata command used to clear saved variables after each level.
