### ISSUE TITLE
Some tokens/pickups have their textures displaced from the objects

### ISSUE THREAD

**Issue by ReeseWB-001** [TheLegendOfMataNui/game-issues#141]
This is an issue in the Beta version.
For one egregious example: in TA07 in Tahu's level, there are some token textures underneath the lava. These tokens are placed directly beneath some platforms, meaning that they were intended to be placed on top of those platforms. However, landing on these platforms causes you to collect these tokens, meaning that the textures are displaced.
This also occurs in Kopaka's level and Lewa's level, and most likely a few others.

**Comment by ShadowOfNight** [comment]
This was fixed in a previous patch.
