### ISSUE TITLE
My game opens as a white screen and displays a message 

### ISSUE THREAD

**Issue by Chickenmandan** [TheLegendOfMataNui/game-issues#142]
Build Version:
Beta: v1.0.0

So when I open the beta version from the launcher the game is a white screen with music playing 
and in a separate tab displays a message saying 
 unhandled exception: c0000005
 at address: 10021248
Im playing on a windows 8 Toshiba laptop

**Comment by ShadowOfNight** [comment]
If you have DGVoodoo in your Lego Bionicle directory, open it and go into the DirectX tab; make sure "Disable and passthru to real DX" is checked.  Then try running the game again.

**Comment by Jezzco** [comment]
I have the same problem, but when I try to open DGVoodoo it won't open. Any help?
Im using a Windows 10 computer.

**Comment by ReeseWB-001** [comment]
@Chickenmandan Are you still having this problem?

**Comment by Vahkiti** [comment]
This has recently been discovered to be most likely to be your antivirus flagging one or more files in the mods folder. Please make sure that's not happening, and the issue should be resolved.
