### ISSUE TITLE
Failing a timed challenge in Makuta's level fails to reset text size

### ISSUE THREAD

**Issue by ReeseWB-001** [TheLegendOfMataNui/game-issues#143]
This is an issue with both the Alpha and Beta versions.
When the time in one of Makuta's challenges reaches the final ten seconds, the timer text turns red and grows slightly larger. When the time runs out and the Toa respawns, the text does not shrink back to its original size.

**Comment by ShadowOfNight** [comment]
This is now fixed for all builds (Alpha, Legacy Beta, Rebuilt) and will be in the next release.  Closing ticket.
