### ISSUE TITLE
Entering GLY3 from WTHK fails to cancel the sliding physics

### ISSUE THREAD

**Issue by ReeseWB-001** [TheLegendOfMataNui/game-issues#144]
This is a problem in the Beta build.
This makes it impossible to swim, thus impossible to complete the level. You instantly cling to the bottom of the seafloor, unable to swim upwards.

**Comment by ReeseWB-001** [comment]
It is worth noting that this worked fine in the alpha, where the map transitioned into GLY1.

**Comment by ShadowOfNight** [comment]
Fixed the cleanup problem that was causing this; issue closed.
