### ISSUE TITLE
Falling into the water in CLF1 causes a Toa Kaita sound to play

### ISSUE THREAD

**Issue by ReeseWB-001** [TheLegendOfMataNui/game-issues#146]
This is an issue in the Beta build.
Specifically, the sound is called "ToaKaitaConverseMediumRegular2" (It can be found in the Alpha's files for reference). I can't think of any reason why this would happen.

**Comment by ShadowOfNight** [comment]
There's a very good reason for this: the osi is referencing that sound entry in the soundtable.slb.  This means that each killbox individually needs to be given a sound.  

Simple fix is to change the entry the killbox is referencing.  So, naturally I used the falltodeath sound effect.
