### ISSUE TITLE
Aside from Whenua, no Turaga have doors that block entrance before intended

### ISSUE THREAD

**Issue by ReeseWB-001** [TheLegendOfMataNui/game-issues#149]
This is an issue in the Beta version.
In Onu-Koro, Whenua's hut has a door that remains closed until the Rahi attacking the village are defeated. None of the other Turaga have such a door, meaning that the Turaga can thank you for saving the village while the Rahi are still attacking the village.

**Comment by ReeseWB-001** [comment]
To clarify slightly, some of the huts do have door textures (in Ga-Koro and Po-Koro), but you can still enter the hut while the door is "closed," and the door texture does not disappear when the Rahi are defeated. In Ko-Koro's case, there isn't a door texture, but rather it seems like the wall behind the hut in clipping into the door (though you can still enter). In Le-Koro, there is no door texture at all, despite one being present in the Alpha. In Ta-Koro, there are no Rahi attacking inside Ta-Koro, so the thank you message doesn't make much sense. Additionally, the place where Vakama's hut was in the Alpha does have a door texture over it, but no longer transitions to the hut (the hut instead being the former Takara stage).

**Comment by ShadowOfNight** [comment]
@Vahkiti What is the game plan here for this in Legacy?  Same thing?  Or do we leave those without doors.

**Comment by ReeseWB-001** [comment]
The only doors remaining to put in are Nuju and Matau's.

**Comment by Vahkiti** [comment]
This will be fixed as of REBUILT 1.1. Will remain as-is for Legacy since it's not necessarily a bug, just an unfinished feature.
