### ISSUE TITLE
Gali loaded game crash

### ISSUE THREAD

**Issue by ShadowOfNight** [TheLegendOfMataNui/game-issues#15]
Quitting from the second area of Gali's level and reloading the saved game causes the player to disappear and experience a death loop, followed by a crash.

**Comment by Vahkiti** [comment]
IIRC, loading a save ANYWHERE in Gali's level causes a death loop if you enter water. Not sure if these two are related or not however.

**Comment by ShadowOfNight** [comment]
All of the loading issues in Gali's level across both builds were broken due to the grapple hook code having way too many arguments, plus the subroutine in question was checking for too many functions in-general.
