### ISSUE TITLE
Huna-resistant bat and L1A7 crash (also happens in TA12)

### ISSUE THREAD

**Issue by PeabodySam** [TheLegendOfMataNui/game-issues#150]
This is in the **beta** and does not seem to be an issue in the alpha.  This is also a Windows 7 computer, for whatever that may be worth.

I have frequently had trouble with L1A7 when attempting to play through Onua's level. You're supposed to use the recently-acquired Kanohi Huna to jump across the platforms without them collapsing beneath you. You only have just barely enough energy to make it across the room with the Huna. However, at the other end of the chasm is a Rahi bat nest, and when you make it to the last platform, the bat is aggroed and attacks Onua. This is an error, because Rahi should not become aggroed while the Huna is in use. The only way around this is to shoot the nest and bat before attempting to cross the chasm.

Unfortunately, that's not the only issue in L1A7. The bat attacking Onua may slow him down long enough for the Huna to run out of energy, causing the final platform to collapse underneath him. I'm not certain if this is the specific cause, but the effect is yet another "unhandled exception" crash, at address **0055ff98**. While it's not consistent (because this game is apparently coded by quantum physicists), I've experienced this specific crash multiple times, making it rather easy to reproduce for submitting this issue.

![l1a7 crash](https://user-images.githubusercontent.com/36681899/40571360-6bf4603a-6065-11e8-91e1-754b5407dd5b.png)

**Comment by ReeseWB-001** [comment]
This is not a Windows 7 exclusive issue. L1A7 does have some crashing problems, but as far as I can tell, they only happen when you're playing through the level normally. When I warp to L1A7 immediately after beginning the level, the crashes don't happen. I don't know what trigger in the level causes this.

The Rahi, however, is an issue no matter how you get to L1A7. Oddly, the Huna seems to work after you've scared the Rahi off first by destroying the nest, but not before.

**Comment by PeabodySam** [comment]
Attempted another playthrough of Onua's level, only to crash at L1A7 again when a mistimed jump caused Onua to fall to his death. This time, I noticed a different crash address: **00560018**. Thought this might be relevant, though (as someone with zero programming knowledge) I'm not sure how.

**Comment by OndrikB** [comment]
The same crash can also happen if you:
1. Step on the branch with the tokens on it
2. Kill the hive that opens the door
3. Shoot a stalactite in TA12 (00560018)

**Comment by ReeseWB-001** [comment]
The sound buffer crash has been fixed, but the bat still ignores the Huna.

**Comment by LennyTheBionicleLover** [comment]
In Onua’s level in Rebuilt, when I was using the Huna, the bats attack me while I am using the Huna’s power. :(

**Comment by ShadowOfNight** [comment]
This has been completely resolved and will be included in both the next Legacy Beta and Rebuilt patches.  This turned out to be an issue with the rendering limit being too low.  Entities that are not rendered yet do not have the Huna's effects applied retroactively.  Closing ticket.
