### ISSUE TITLE
Dying in PZZL spawns you in a bad position

### ISSUE THREAD

**Issue by ReeseWB-001** [TheLegendOfMataNui/game-issues#151]
Had a hard time finding a proper name for this bug. Not entirely sold on the one I used.
When dying in Onua's PZZL (the area with the Kanohi Ruru), you respawn in an area of the entrance that's a bit odd. If you move forwards, you'll continue into PZZL normally. However, if you move back a bit first, you are stuck in between the loading zone for ATRM and the edge of the map. Move forwards now, and you'll transition into ATRM. Move back, and you'll fall off the map and get an out-of-world death crash.

**Comment by ReeseWB-001** [comment]
Video example: https://youtu.be/dyYrjICnv24
It seems this happens when the Rahi kill you specifically, as it did not happen when using the debug menu to die.

**Comment by OndrikB** [comment]
As shown by my speedrun, dying while picking up the Ruru doesn’t cause this issue to occur.

**Comment by ShadowOfNight** [comment]
Seems to have been fixed; closing this issue.
