### ISSUE TITLE
I try to talk to any cpu but no text appears on screen

### ISSUE THREAD

**Issue by emher927** [TheLegendOfMataNui/game-issues#152]

**Comment by PeabodySam** [comment]
Is this what you see?

![kapura](https://user-images.githubusercontent.com/36681899/41259140-7d790142-6da0-11e8-8e6e-acbdb11b7e7d.png)

I had this problem when I attempted to run the game without dgVoodoo.

**Comment by ReeseWB-001** [comment]
@emher927 Are you still having this issue?

**Comment by Vahkiti** [comment]
Closing since the OP has not responded in over a year. Will reopen if still relevant.
