### ISSUE TITLE
Sequence break in Kopaka's VISN area

### ISSUE THREAD

**Issue by OndrikB** [TheLegendOfMataNui/game-issues#153]
**Build Version:**

"Beta" October 23, 2001

**Steps to Reproduce:**

Use the Kanohi Matatu to place the block underneath yourself (works with the 's' key).
Look into the direction you want to be launched into and carefully fine tune the block's location into you.
Get launched.

This issue is probably caused by the fact that Kopaka tries to push the block away from himself, but because it just always gets snapped into him (Matatu) he will do this indefinetly.

https://youtu.be/RVsWgYtlfRc
Youtube video with inputs.

Currently, this is the only way to beat this level without use of the debug menu, but you will probably run out of energy anway if trying to collect the Akaku too.

**Comment by OndrikB** [comment]
Also affects TELE, or any area with a Matatu block for that matter.

**Comment by ReeseWB-001** [comment]
Since this is a sequence break that is difficult to perform, this is not considered an issue. Being closed and given the Sequence Break tag.
