### ISSUE TITLE
Disk-throwing Ta-Matoran falls into lava

### ISSUE THREAD

**Issue by PeabodySam** [TheLegendOfMataNui/game-issues#154]
This is an issue in the **beta**, though I haven't checked the alpha to see if it's also relevant.

In VLLG of Tahu's level, the Ta-Matoran who lost his throwing disk (orange huna, purple feet) is positioned precariously close to a pool of lava.  Due to his wandering AI, he will walk towards the lava and then fall in.  If this happens, he cannot get out, and the player is unable to talk to him.  The only way to "save" him is to reload VLLG (e.g. entering and exiting TURA), and even then the player is given only a few seconds before he goes swimming in lava again.

![suicidal ta-matoran](https://user-images.githubusercontent.com/36681899/40623149-5b5cb1c2-6273-11e8-8b02-87f2830ead4e.png)

**Comment by ShadowOfNight** [comment]
Fixed by freezing him in place via the osi.

**Comment by ShadowOfNight** [comment]
OSI fix has been removed upon request from Vahkiti.  Reopening for now.

**Comment by ShadowOfNight** [comment]
Fixed again by freezing matoran in place.  Closing this issue for good now.
