### ISSUE TITLE
Tahu's TA02 (ver 2) and SHRN cause music glitch

### ISSUE THREAD

**Issue by PeabodySam** [TheLegendOfMataNui/game-issues#155]
This is an issue in the **beta**.

When the player visits Tahu's SHRN for the first time, a cutscene will play.  Once the cutscene finishes, SHRN will use the music of whatever area the player previously visited (see #158).  If this happens, then that particular music track will play over all other music tracks in the game.  This continues until the player shuts down the game.

For example, if the player warps to SHRN from FVIL, then "Lego Underground" (the music track of FVIL) will play in SHRN.  Then, if the player enters TA12, "Lego Underground" and "Makuta Theme" (the music track of TA12) will play at the same time.  If the player quits to the level select menu, then "Lego Underground" and "Gali Ambience" will play at the same time.

EDIT: Updating this to note that this same glitch happens with TA02.  More specifically, the second version of the area (with the dried lava) accessed after TA05.  The only difference is that the music is guaranteed to be "Makuta Theme", rather than whatever music was playing in the previous area (which, in this case, would be "Tahu Theme").

**Comment by ShadowOfNight** [comment]
@PeabodySam Update: managed to fix this entirely.  Closing issue.

**Comment by ShadowOfNight** [comment]
Fixed for good this time
