### ISSUE TITLE
Kopaka's VLLG trees have odd collision

### ISSUE THREAD

**Issue by PeabodySam** [TheLegendOfMataNui/game-issues#156]
This is an issue in the **beta**.

Some of the trees seen in Kopaka's VLLG have collision that treats them like slopes.  Because their lowest branches are so close to the ground, Kopaka can "climb" these trees by simply walking towards them, without even needing to jump.  Therefore, wandering Ko-Matoran can likewise "climb" the tree, where they often get stuck because they keep walking towards the trunk rather than away from it.

![kopaka has weird taste in christmas tree decorations](https://user-images.githubusercontent.com/36681899/40623651-f3da3f6c-6275-11e8-86e7-4fbe627486a9.png)

**Comment by ShadowOfNight** [comment]
This has been addressed in Rebuilt, but is being left in as a quirk of Legacy Beta (also because it's frankly funny).  Closing this issue as a result
