### ISSUE TITLE
Tahu's level begins with FVIL, not MTUP

### ISSUE THREAD

**Issue by PeabodySam** [TheLegendOfMataNui/game-issues#157]
This is an issue in the **beta**.

When starting Tahu's level from the level select menu, the game begins with FVIL.  However, Tahu's MTUP is fully-functional (unlike Gali's MTUP, which crashes when the cutscene is finished), and since both Pohatu and Lewa begin their levels with MTUP when started from the level select, I'm not sure why the game doesn't start Tahu's level at MTUP.

**Comment by ReeseWB-001** [comment]
This issue has been fixed and will be included in the next patch.
