### ISSUE TITLE
Areas with "unassigned" music tracks

### ISSUE THREAD

**Issue by PeabodySam** [TheLegendOfMataNui/game-issues#158]
This is discussing the **beta**.

A significant number of areas in the game do not have a specific music track assigned to them.  When playing the game, this causes these areas to continue playing the music track of the previously-visited area (for example, visiting TURA will continue playing whatever music was playing in VLLG).  The only exception is Onua's level, where every area has an assigned music track.

Gali:
- STRT (plays "Gali Ambience" when loaded from level select)
- TURA

Pohatu:
- MTUP (plays "Pohatu Ambience" when loaded from level select)
- TURA

Kopaka:
- TURA

Lewa:
- TURA
- HIVE
- BOSS (switches to "Lewa Theme" once the Air Elemental cutscene begins)

Tahu:
- TURA
- BOSS (switches to "Tahu Theme" once the Fire Elemental cutscene begins)
- SHRN (also causes audio glitch; see #155)
- TA05 (switches to "Tahu Theme" after the lavaboard cutscene plays)

Makuta:
- ONUA (plays "Gali Ambience" when loaded from level select)
- GALI
- PHTU
- KPKA
- LEWA
- TAHU

**Comment by PeabodySam** [comment]
A few suggestions for consideration:

- All TURA should use "Village"
- Gali's STRT could use "Gali Ambience", like it currently does
- Pohatu's MTUP could use "Pohatu Ambience", like it currently does
- Lewa's HIVE could use "Part 2 Lego Underground", since that's the track used in the cutscene
- Lewa's BOSS could use "Lewa Ambience" or "Lewa Drum and Bass"
- Tahu's BOSS could use "Part 2 Lego Underground" or "Lego Underground"
- Tahu's SHRN should use "Shrine"
- Tahu's TA05 could use "Part 2 Lego Underground", since that's the track used in the cutscene
- All Makuta levels could use "Makuta Theme"

**Comment by ReeseWB-001** [comment]
Pohatu's BOSS also has no music track after you collect the Makoki Stone, meaning the collection track loops endlessly.

**Comment by ShadowOfNight** [comment]
I've already made some of these adjustments, so I'll see about finishing this up.

**Comment by ShadowOfNight** [comment]
@PeabodySam @robot5431 
I have completed assigning music to these area.  Apparently missing music is one of the main causes for the music loop bug seen notably in Tahu's TA02 and SHRN.

I will not assign music to Pohatu's, Lewa's and Tahu's bosses primarily because it appears it was done to make the completion music function properly (although Pohatu's does not).  I may revisit this, but for now I'm closing the issue.
