### ISSUE TITLE
Quitting crashes/shutdowns

### ISSUE THREAD

**Issue by ShadowOfNight** [TheLegendOfMataNui/game-issues#16]
Alpha
----
Quitting from the following areas will cause the game to crash:
BUGS, SCRP, SPCV, HK01, and MUD0.

Beta
-----
Quitting from these areas cause a shutdown: HK01, SHRN

**Comment by ReeseWB-001** [comment]
Level 2 (beta):
STRT

**Comment by spmoc045** [comment]
From onua's beta shrn - there's a one-time crash, after completing the "trials".

Error 1001d6d3

**Comment by spmoc045** [comment]
Beta, gali

vllg-vlgs transition
Same but one-way error

vlgs-vllg-strt (yes) transition
After completing vlgs move to strt. Error 6b4bad49, restart - normal spawn in strt

**Comment by LennyTheBionicleLover** [comment]
Is that fixed, yet?

**Comment by ShadowOfNight** [comment]
All of these quit crash issues listed in this issue have been addressed or will be addressed in the next patch.  Closing issue.
