### ISSUE TITLE
Failing RKFL or SNFL might not properly reset bridge

### ISSUE THREAD

**Issue by PeabodySam** [TheLegendOfMataNui/game-issues#160]
This is an issue in the **beta**.

In Pohatu's RKFL and Kopaka's SNFL, the player must defend a bridge from an infinite number of rolling boulders.  If the player fails this challenge, then the boulders will smash the bridge and the Toa will fall to his death.  When the Toa respawns, the bridge has a significant chance of not being reset correctly, often times with entire chunks misplaced that may make it impossible to reach the door and complete the challenge.

![broken bridge](https://user-images.githubusercontent.com/36681899/40629053-d9c745ae-6296-11e8-958f-27a4d4240ead.png)

**Comment by OndrikB** [comment]
Fixed.
