### ISSUE TITLE
Lewa's SHRN cutscene audio is not synced properly

### ISSUE THREAD

**Issue by PeabodySam** [TheLegendOfMataNui/game-issues#162]
This is an issue in the **beta**.

The alpha featured a forty-second long cutscene of Lewa riding a Nui-Rama to Le-Kini when traveling from HIVE to SHRN.  This cutscene was heavily trimmed down in length in the beta.  However, the audio file (legocineLewaWaspDismount.mp3) remains unchanged and therefore no longer syncs properly with the abridged cutscene.  For example, the Nui-Rama can be heard flying while it's sitting completely still.

Two possible solutions.  On one hand, we can edit the audio file and cut out the beginning so it syncs properly.  On the other hand, we might be able port over the full-length cutscene from the alpha.

**Comment by ShadowOfNight** [comment]
For the legacy patch the audio should be shortened.  For the Rebuilt patch, the alpha cutscene has been ported.

**Comment by ShadowOfNight** [comment]
Fixed
