### ISSUE TITLE
Dying in MAZ2 hides the UI

### ISSUE THREAD

**Issue by PeabodySam** [TheLegendOfMataNui/game-issues#166]
This is an issue in the **beta**.

If Kopaka dies in MAZ2, the UI disappears upon respawning.  This can be corrected by switching masks or entering a different area.  Using the debug menu and warping to another area while this glitch is in effect will keep hiding the UI until Kopaka switches masks, enters a different area, or dies again.

It's not that big of a deal, and honestly it makes me wish there was a method of manually hiding the UI.  Still, I figured I'd document it here.

![medium wolfrat](https://user-images.githubusercontent.com/36681899/40669975-3ad96882-6336-11e8-8ad0-7f298ebae888.png)

**Comment by ShadowOfNight** [comment]
This is likely due to the osi subroutines for MAZ2 not having proper hud "hide" and "show" commands.

**Comment by ShadowOfNight** [comment]
Fixed this by altering the order of the code in the MAZ2 onevent subroutine within the OSI.
