### ISSUE TITLE
The method to damage the Taratoka-Nui does not function

### ISSUE THREAD

**Issue by ReeseWB-001** [TheLegendOfMataNui/game-issues#170]
In the boss room for Tahu's level, there are stalactites that are placed directly above the Taratoka-Nui when it pops out to attack:
![bandicam 2018-06-02 08-54-41-992](https://user-images.githubusercontent.com/37253627/40877222-b3f830ea-6642-11e8-9a30-3ae4648a1ef9.jpg)

These stalactites are presumably the way to damage the Taratoka-Nui, as there is evidence that the stalactites can be broken (I found this while switching Toa mid-fight):
![bandicam 2018-06-01 14-55-21-028](https://user-images.githubusercontent.com/37253627/40877243-ff71dca6-6642-11e8-9cbd-2c7c3dd0fef2.jpg)

However, there is no way to cause the stalactites to fall, thus the Taratoka-Nui cannot be damaged and, by extension, defeated.

**Comment by PeabodySam** [comment]
It may be worth noting that shooting at the stalactites caused them to fall in alpha v0.006, just as expected. For some reason, only the beta is affected by this bug.

**Comment by robot5431** [comment]
This is a slightly different issue in the alpha, as the damage function works, but the boss is unkillable due to it destroying all the footholds after enough hits.

**Comment by ReeseWB-001** [comment]
Video example of the alpha fight: https://youtu.be/x2KLiV5nsL4

**Comment by ReeseWB-001** [comment]
For the beta, the stalactites not falling is an FPS issue. At 30, they will fall when shot (if you're lucky, it's rather inconsistent). However, this only stuns the Taratoka, and there seems to be no way to actually damage it (Volcano does nothing, and the elemental spheres are ineffectual).

**Comment by OndrikB** [comment]
some more things (might not be relevant to solving the issue, but worth noting regardless):
when aiming at the dragon's neck while it's stunned, the crosshair is green, meaning that the weak spot is probably supposed to be there
The stalactites are just invisible when dropped. I can literally hit the dragon with nothing and it's stunned
The dragon is supposed to be able to be hit with elemental powers while in "KnockoutState", it would play "TahuSwordImpact" though, however there is no way to get close enough to the dragon in order to get a melee attack, not even by jumping on the neck.

**Comment by ReeseWB-001** [comment]
To add to the above statement, Vakama's dialogue in SHRN mentions that you need to use the sword somehow. Quote: "Use all your powers and abilities to defeat this beast, especially your flaming sword."

**Comment by OndrikB** [comment]
To add to everything, a tailsmack can be triggered by shooting a stalactite during the dragon's "taunt". This will destroy a huge chunk of the platform and afterwards, the dragon will reappear inside it. This can be repeated until just a circle is remaining and also allows the player to stun the dragon into lava, which however doesn't trigger a damage function.
After doing this enough times, the dragon can disappear entirely (though the health bar will still be visible) or the player can be stuck in an infinite loop

This shows that the dragon most likely wasn't ever coded to take damage in the first place

**Comment by ReeseWB-001** [comment]
Thanks to the efforts of @JrMasterModelBuilder , the dragon now is hittable with Tahu's melee attack after being knocked out. This issue will remain open until the stalactites are fixed to work at any FPS.

**Comment by OndrikB** [comment]
Issue resolved thanks to the efforts of @JrMasterModelBuilder 
![tahuboss_perfect](https://user-images.githubusercontent.com/38321117/47621173-286e6900-daf4-11e8-9e60-dc8cd9b60b36.png)
