### ISSUE TITLE
After Approving it to change things, Nothing opens.

### ISSUE THREAD

**Issue by LeithalWolf** [TheLegendOfMataNui/game-issues#172]
I got the launcher from the biomedia page and I believe it's the most recent build. I get no error message, nothing. The mouse turns into a spinning wheel, then nothing ps: It's Windows 10

**Comment by ReeseWB-001** [comment]
@LeithalWolf Are you still having this problem?

**Comment by LeithalWolf** [comment]
No, I did some digging and miraculously it worked

**Comment by PinkRei** [comment]
wanna maybe say what kind of digging you did so other people with the same problem can find a solution as well?

**Comment by LeithalWolf** [comment]
This happened maybe a year ago so I don’t remember sorry.
