### ISSUE TITLE
Maps with bad killboxes

### ISSUE THREAD

**Issue by ReeseWB-001** [TheLegendOfMataNui/game-issues#175]
This thread should be used to document any maps with improper killboxes (bad placement, lack thereof, etc).

To start:
~Onua - L1A7, L1A8 (only when the village is saved, for some reason)~
~Gali - WTHK~
~Pohatu - BOSS~
~Kopaka - BRD3, BRD4~
~Lewa - Most of them, honestly. That one vine in LE03 is notable. LE04~
~Tahu - Certain lava areas function differently, killing you so man times that the game crashes. TA02~

**Comment by OndrikB** [comment]
To me, L1A7 also crashes on death when I didn't save the village

**Comment by ShadowOfNight** [comment]
All of these have been fixed, therefore closing
