### ISSUE TITLE
The Kaukau doesn't show up in MWAT most of the time

### ISSUE THREAD

**Issue by ReeseWB-001** [TheLegendOfMataNui/game-issues#186]
No clue as to why, but the Kanohi Kaukau only occasionally shows up in MWAT, locking you in the room with no chance of escape.
On Win8, it seemingly does not appear at all.

**Comment by OndrikB** [comment]
Issue resolved. (at least on Win10)

**Comment by robot5431** [comment]
Resolved on Win8. No idea what caused it not to work, but it's there now consistently.

**Comment by ReeseWB-001** [comment]
This was apparently an issue regarding the mask's texture, which for some reason was causing it to not spawn it upon the defeat of the Rahi.
