### ISSUE TITLE
For certain levels, transitioning from one level to another while having the Ruru active fails to deactivate the green filter

### ISSUE THREAD

**Issue by ReeseWB-001** [TheLegendOfMataNui/game-issues#187]
Transitioning from Gali's level to Pohatu's level, Pohatu to Kopaka, or Kopaka to Lewa while having the Kanohi Ruru active causes the green night vision filter to remain active, only going away once the Ruru is turned on and off again. This causes the cutscenes to look strange, along with the rest of the level, until the mask is switched off as previously described.

Video example: https://youtu.be/hc0KWUXHKKs

**Comment by ShadowOfNight** [comment]
Saffire apparently never added the cleanup call for these areas to switch mask powers off.  Most likely due to the fact that mask powers were disabled in these areas by default.  Restoring these cleanup calls fixes this issue entirely.  Closed.
