### ISSUE TITLE
Certain HUD graphics don't change upon Toa change in Makuta

### ISSUE THREAD

**Issue by ReeseWB-001** [TheLegendOfMataNui/game-issues#189]
The energy ball texture on the HUD is always Tahu's, and Kopaka's token texture stays as Pohatu's for some reason.

**Comment by OndrikB** [comment]
The energy ball thing is level-dependent. In the Frontend the energy ball texture is also Tahu's. The only way that could be fixed would be to add the Makuta stages into their respective level or to make each Makuta area it's own level.

**Comment by ReeseWB-001** [comment]
Resolved in 1.4/1.0.1.
