### ISSUE TITLE
Leaving Kopaka's STRT in latest alpha patch causes a shutdown

### ISSUE THREAD

**Issue by OndrikB** [TheLegendOfMataNui/game-issues#191]
**Build Version:**

0.006 Alpha 

**Steps to Reproduce:**

Go to Kopaka's STRT
Try to get out (warping, legit or debug camera, doesn't matter)

**Comment by OndrikB** [comment]
This can be circumvented by Loading the game, but it might not work because of #190

**Comment by ShadowOfNight** [comment]
Fixed.  Moved the cinematic cleanup code a bit and it seems to be working now.
