### ISSUE TITLE
Front end's "Glossary" option starts at Huki

### ISSUE THREAD

**Issue by OndrikB** [TheLegendOfMataNui/game-issues#192]
**Build Version:**
"Beta" October 23, 2001

**Steps to Reproduce:**

Go to the front end
Select "Options"
Select "Glossary"

It starts at Huki, and arrow up just makes it go back to the options menu.

**Comment by OndrikB** [comment]
This issue also applies to the end of the "Glossary", as it ends at Turaga Whenua rather than Wahi

**Comment by ShadowOfNight** [comment]
Fixed.
