### ISSUE TITLE
Pohatu level crashes

### ISSUE THREAD

**Issue by ShadowOfNight** [TheLegendOfMataNui/game-issues#20]
Warping to BLGF, BLR1, BLR2, BLR3, BLR4, and BLR5 all cause a crash IF you loaded Pohatu's level first.  If you warp to these areas after loading another level, the game doesn't flip out.  Warping to BLCR works and should be done first in order to access the BL areas, since you need to be riding the Kane-Ra apparently.  Warping to BLCR and the to the next area, BLR1 is treated as though you proceeded to BLR1 on foot and places you onto the Kane-Ra.

**Comment by Vahkiti** [comment]
This is likely normal behaviour since the game doesn't know how to proceed with loading those areas on foot. Marking as resolved until further evidence is given to suggest otherwise.

**Comment by ShadowOfNight** [comment]
BLR1 and BLR2 crash in the beta if you warp there while not on the bull, as to be expected.  As this is something that really doesn't need a fix, I'm closing this issue.
