### ISSUE TITLE
Certain points in Kopaka's SHRN freeze the game

### ISSUE THREAD

**Issue by ReeseWB-001** [TheLegendOfMataNui/game-issues#200]
A certain point on the ice bridge after the SNBD exit freezes the game, as does a certain point in the path leading to ICMZ.

**Comment by ReeseWB-001** [comment]
The ICMZ path freeze only seems to happen after backtracking from ICMZ to SHRN.

**Comment by ShadowOfNight** [comment]
Fixed the ice bridge freeze by replacing the collision data for the area.  

EDIT:  This also somehow fixed the freezing when entering from ICMZ.  Closing issue.
