### ISSUE TITLE
Kopaka's CRSS layout could use a reorder

### ISSUE THREAD

**Issue by OndrikB** [TheLegendOfMataNui/game-issues#201]
The section leading up to VISN (the room with the Akaku) in CRSS can only be reached by invisible platforms. These platforms, however, are invisible until you get the Akaku. I think you see where I'm going with this.

Because of this, it's almost impossible to progress through Kopaka's level legitimately unless you've memorized the exact movement patterns of the invisible platforms.

My suggestion would be to swap VISN and SNBD, which is easily done.
As in instead of it being SNBD -> CRSS -> VISN -> BRD3 -> SHRN 
it would be VISN -> CRSS -> SNBD -> BRD3 -> SHRN

**Comment by ReeseWB-001** [comment]
To be fair, if the grapple point worked ( #181 ) then you could complete the map using Kakama jumps from the icicle platforms you can shoot down.
The invisible platforms are most likely there for if you are backtracking through the level for tokens and don't want to do the icicle bit again.

**Comment by OndrikB** [comment]
"The invisible platforms are most likely there for if you are backtracking through the level for tokens and don't want to do the icicle bit again."

If you look at where the invisible platforms are, you can easily dismiss this claim - they're meant to work with the icile bit.

**Comment by ReeseWB-001** [comment]
Yet the section is still possible without them. They are just there to make it easier once you have the Akaku.

**Comment by ShadowOfNight** [comment]
I fixed the grapple point (#181 ), which makes normal progression through this area possible with the Kakama.  As this area can now be completed normally, I see no reason to reorder the maps.  Issue closed.
