### ISSUE TITLE
BLR2 crashes on exit

### ISSUE THREAD

**Issue by ReeseWB-001** [TheLegendOfMataNui/game-issues#203]
This is apparently an issue with the bull and/or Pohatu not being removed properly.

**Comment by ReeseWB-001** [comment]
The crash itself has been fixed, but this issue will remain open until all associated problems are resolved as well (the level crashing on exit after dismounting the Kane-Ra being the main problem).

**Comment by ShadowOfNight** [comment]
Problems seem to have been resolved, so I'm closing this.
