### ISSUE TITLE
BLR6 crashes on exit

### ISSUE THREAD

**Issue by ReeseWB-001** [TheLegendOfMataNui/game-issues#204]
Seems to be the same issue as #203 , but due to them acting somewhat differently this issue will be separate.
Unlike the BLR2 crash, the PTOS cutscene may actually load, only Pohatu is missing. As soon as the cutscene ends, the game crashes.

**Comment by ShadowOfNight** [comment]
Added proper code to cleanup subroutine for area, which prevents a crash.  Issue closed.
