### ISSUE TITLE
Invisible Dancing Matoran

### ISSUE THREAD

**Issue by spark-slizer** [TheLegendOfMataNui/game-issues#209]
So I'm playing the alpha version and when I reach the village of onu-koro, I see random shadows, so I press space on them and they said they're dancing but they cannot be seen.

How do I fix this?

**Comment by spark-slizer** [comment]
Update: it isn't just Dancing Matoran, its any matoran who is not walking.

**Comment by OndrikB** [comment]
Get the patches

**Comment by spark-slizer** [comment]
I already have them

**Comment by Vahkiti** [comment]
Is this still relevant?

**Comment by ShadowOfNight** [comment]
@onepublegh Is this still an issue for you?

**Comment by ShadowOfNight** [comment]
This will be fixed once and for all in alpha patch 1.2.0.  Closing issue
