### ISSUE TITLE
Tohunga in cutscenes are reused via teleportation based on camera angles

### ISSUE THREAD

**Issue by Vahkiti** [TheLegendOfMataNui/game-issues#216]
This issue is consistent across builds. Though not necessarily one with the default game setup, the recent addition of custom Tohunga body colours has made it obvious. Tohunga used in cutscenes such as the Takara are teleported around to give the illusion of there being more than a preset number of them in the scene. Though most likely done by Saffire to conserve assets, this causes issues when we want certain Tohunga in the optional patch to be unique. (Eg: Nobua, Taipu)

**Comment by epicabsol** [comment]
Right, so, what do you want done about it?

**Comment by Vahkiti** [comment]
Essentially a cutscene hook that will call settohunga whenever the cutscene physically moves an actor so we can change not only where they are, but who.

**Comment by Vahkiti** [comment]
Issue closed for now since it is currently being worked around with animation edits.
