### ISSUE TITLE
The launcher exe does literally nothing

### ISSUE THREAD

**Issue by PinkRei** [TheLegendOfMataNui/game-issues#220]
**Remember to add the following information:**

**Build Version:**

"Beta" October 23, 2001

**Steps to Reproduce:**

Run the launcher exe file.

It has been installed and set to windows xp service pack 3 compatibility mode. My operating system is Windows 10. Double clicking the exe causes the UAC confirmation to allow it to make changes to my computer to appear, and when clicking yes, that window disappears and then nothing happens. It's very infuriating not to be able to do any troubleshooting when there's no event to troubleshoot.

**Comment by PinkRei** [comment]
Also it's worth pointing out that the instructions on the biomedia website say "Go to the install directory, go to the properties of BIONICLE.exe, select “Run as Administrator”, and set the compatibility mode for the executable to Windows XP.". There IS NO FILE CALLED "BIONICLE.exe" in the install directory. The only one I could find is called "Lego BIONICLE.exe", which I could only assume is what the instructions are referring to. This is the file that I have to set to windows xp compatibility. If this is incorrect I would greatly appreciate some clarification on where the file called "BIONICLE.exe" is located

**Comment by 2Tie** [comment]
That step in the instructions was originally written before the launcher was made, and the Alpha had the game executable labelled as simply BIONICLE.exe. You are correct in that the steps need to be done to "Lego BIONICLE.exe" in the beta version.
