### ISSUE TITLE
Whenua Legend FMV problems

### ISSUE THREAD

**Issue by OndrikB** [TheLegendOfMataNui/game-issues#221]
The idea to have the "Legend" play in an FMV is a really bad idea and here's why:

The text for an FMV is, to my knowledge, fixed. Meaning that on language change, the text would stay in English. This is a problem that could be fixed by either changing what FMV plays based on the language (meaning that you'd have to have 1 FMV per language) or to have a cinematic play over it, which isn't possible as far as I know.

Another issue with it is that it always plays on entry into the TURA area and not just once.

**Comment by Vahkiti** [comment]
Fixed in 1.0 of Rebuilt
