### ISSUE TITLE
First entry in the location table in cin_char slbs is unused.

### ISSUE THREAD

**Issue by OndrikB** [TheLegendOfMataNui/game-issues#229]
This entry apparently governs where characters are at the start of a cutscene, as the second one governs where they are at the end. Will require a hookmod to make it used.

**Comment by epicabsol** [comment]
Implemented with https://github.com/TheLegendOfMataNui/LOMNHook/commit/59942c0cd4f7f66b3ca28a1c340c0272173a2488.

**Comment by epicabsol** [comment]
Added rotation with https://github.com/TheLegendOfMataNui/LOMNHook/commit/9ba0ed7812fa74668d2f6f3d07566b6bd48b4e76.
