### ISSUE TITLE
HK01's hook boxes should be moved above their platforms

### ISSUE THREAD

**Issue by ReeseWB-001** [TheLegendOfMataNui/game-issues#235]
The current orientation of the boxes is in front of their platforms, occasionally causing issues landing on the platforms. This could be easily remedied by moving the boxes above the platforms themselves.

**Comment by Terrev** [comment]
this is actually yet another issue of "the game requires you to do something it never taught you" which is that you can let go of a grapple early for situations like this (there's another area, in tahu's level, that also requires doing so)

https://www.youtube.com/watch?v=9FxGcoJjIT0

if you do that, the room's actually really easy to consistently clear

but the beta did away with all of the signposts/hints that were in the alpha so [fart noises]
