### ISSUE TITLE
level 6 start crash on full loading

### ISSUE THREAD

**Issue by spmoc045** [TheLegendOfMataNui/game-issues#243]
0.006 Alpha, with and without a save file. Patched with 2018-12-10 21:52

Error 004e7e76

**Comment by spmoc045** [comment]
So, how to start this level: start level 7, move to "tahu", complete it to remove the timer, then move to "fvil", move to the next checkpoing for save, restart game, load save. Exit from "mtup" leads to crash.

**Comment by OndrikB** [comment]
Known, will be fixed in next patch
