### ISSUE TITLE
(Optional) Dead end in fvil

### ISSUE THREAD

**Issue by spmoc045** [TheLegendOfMataNui/game-issues#244]
On the left side from village's gates there's a path with a hole. If you run+jump+hold lmb, then you'll jump over it. There is no teleports at the end.

I assume that this might be a tp to "ta01", since i couldn't find any open doors in village.

0.006 Alpha

**Comment by spmoc045** [comment]
And another one, on the opposite side of the main gate.

**Comment by Vahkiti** [comment]
This exit will be used in some capacity in the first version of Rebuilt.

Issue closed.
