### ISSUE TITLE
Surfing not triggers in some tahu maps

### ISSUE THREAD

**Issue by spmoc045** [TheLegendOfMataNui/game-issues#245]
ta05 (but ta08 is fine) and ta09 (after freefall there's clearly a surfing path), ta12

Alpha

**Comment by Vahkiti** [comment]
TA09 will be fixed in the next patch. (1.1.2) TA05 requires you use the Akaku to acquire a surfboard from under the big ball. TA12 isn't even a surfing map.

Issue closed until further information is given regarding TA12.

**Comment by spmoc045** [comment]
Case closed, sorry.
