### ISSUE TITLE
Respawn in ta14 crashes the game and corrupts save file

### ISSUE THREAD

**Issue by spmoc045** [TheLegendOfMataNui/game-issues#248]
After teleporting to ta13's exit (because i couldn't figure out how to beat it) and dying to door's spikes in ta14 i was respawned above exit to, probably, ta13. Crash.

Alpha

**Comment by Vahkiti** [comment]
Needs more information.

**Comment by Vahkiti** [comment]
Also please make sure to tag your issues properly in the future.

**Comment by spmoc045** [comment]
It was on my 1st playthrough (maybe needs to reinstall with a patch for testing). After respawn i started spamming wasd. I fell through ceiling and after touching ground held s. So i touched the trigger right after respawn in, like, 1-1.5s . After deleting save file everything was working fine.

Windows 10

Similar thing was with ta04 - exit crash on first touch, even with address (for a moment), but without corrupting. And some gali's maps that i can't remember.

**Comment by ShadowOfNight** [comment]
TA14 spawn bug will be resolved in the next patch, along with several save issues related to it
