### ISSUE TITLE
Accessing an "inventory" after picking kanohi Ruru freezes the game

### ISSUE THREAD

**Issue by spmoc045** [TheLegendOfMataNui/game-issues#250]
Beta, after saving a village

**Comment by OndrikB** [comment]
Needs more information

**Comment by spmoc045** [comment]
I entered pzzl from atrm's side, beat it and picked the mask.

**Comment by OndrikB** [comment]
And the inventory screen just didn’t show up?

**Comment by spmoc045** [comment]
Yes. On alt+tab screen the game was shown as working fine, but in-game i just can't do anything other than closing it

**Comment by OndrikB** [comment]
Okay, then I’m closing this as a duplicate of #49
