### ISSUE TITLE
SPCV's entry crash from CLF2's side

### ISSUE THREAD

**Issue by spmoc045** [TheLegendOfMataNui/game-issues#251]
After restart i spawn normally in SPCV. After leaving and re-entering it keeps crashing and so on. Like #68 , i guess?

Beta, after saving a village.

And about labels on the right side - i just can't see this option. [Maybe because i don't have any permissions](https://github.com/KhronosGroup/Vulkan-Docs/issues/15), idk.

**Comment by OndrikB** [comment]
It’s known, but I can’t recall if it was fixed.

**Comment by ShadowOfNight** [comment]
Is this still happening @spmoc045 ?

**Comment by Vahkiti** [comment]
Closing since the OP has not responded in over a year. Will reopen if still relevant.
