### ISSUE TITLE
Some other crashes in gali's levels

### ISSUE THREAD

**Issue by spmoc045** [TheLegendOfMataNui/game-issues#253]
Death in first pit in wthk or any other death
Error 772121f0

Manual teleporting from gly3 to wthk
(random?) Error 77226a0c

Death in gly3
Just a random crash

Beta

I can only add that my videocard is 630m (it's 2012 all over again)

**Comment by ReeseWB-001** [comment]
WTHK has been fixed as of 1.4/1.0.1, and dying underwater is an existing issue.
