### ISSUE TITLE
Launcher doesn't open.

### ISSUE THREAD

**Issue by ulvenAspiration** [TheLegendOfMataNui/game-issues#255]
So i downloaded the Launcher.exe and opened it, but the launcher never opens. i just click it, click allow on the caution text, and then nothing happens. I have no idea what's going on and i'm not sure why.

**Comment by Vahkiti** [comment]
I'll need you to get me a log of what's happened from the Windows event viewer before I can assist you further. As I said to you before, please see this page for more information on how to do so:

https://www.howtogeek.com/123646/htg-explains-what-the-windows-event-viewer-is-and-how-you-can-use-it/
