### ISSUE TITLE
White screen and crash at launch 

### ISSUE THREAD

**Issue by toatahu116** [TheLegendOfMataNui/game-issues#256]
"Beta" October 23, 2001
 After attempting to launch the beta from the launcher, a blank screen pops up and a message that says
"unhandled exception: c0000005 at address: 0052e5d9"
I've spent hours trying to fix this, but to no avail.

**Comment by CameoDaManeo** [comment]
You must either run the game in one of the 4:3 resolution options, or delete the contents of the folder called "Cinematics" in the game directory. Also, make sure that you're running the game in compatibility mode with Windows XP.

**Comment by Vahkiti** [comment]
This has recently been discovered to be most likely to be your antivirus flagging one or more files in the mods folder. Please make sure that's not happening, and the issue should be resolved.
