### ISSUE TITLE
Onua level crash when about to speak to Whenua on kini temple after completing first cave

### ISSUE THREAD

**Issue by mr166** [TheLegendOfMataNui/game-issues#261]
Build Version: Rebuilt v1.0.0

In Onua's level after you've completed the cave segment before going to the earth elemental boss fight, I went to try to interact with Whenua first on the kini temple to see if he had any new dialouge or not. When I hit the interact key near him my game crashed and returned me back to the main menu. Here is the unhandled exception code down below, I'm running on windows 10.

Unhandled exception: c0000005
At address: 0047b34f

![Desktop Screenshot 2019 08 15 - 21 42 54 83](https://user-images.githubusercontent.com/54107118/63092820-5c911880-bfa6-11e9-83d3-d7b4e26c2c05.png)

**Comment by ReeseWB-001** [comment]
@mr166 Have you encountered this issue again since?

**Comment by Vahkiti** [comment]
Closing since the OP has not responded in over a year. Will reopen if still relevant.
