### ISSUE TITLE
Game crashs when exiting to main menu

### ISSUE THREAD

**Issue by mr166** [TheLegendOfMataNui/game-issues#262]
Build version: Rebuilt v1.0.0

When exiting out of the game to return to the main menu, sometimes it crashes at random moments. So far it has only happened when playing through Onua's level but will update if this bug happens in the other toa levels. Here is the unhandled exception code down below, I'm running on windows 10.

Unhandled exception: c0000005
At address: 005769a0

![Desktop Screenshot 2019 08 15 - 22 54 36 01](https://user-images.githubusercontent.com/54107118/63096810-32ddee80-bfb2-11e9-9666-7797d993df6d.png)

**Comment by ReeseWB-001** [comment]
@mr166 Have you encountered this issue since?

**Comment by Vahkiti** [comment]
Closing since the OP has not responded in over a year. Will reopen if still relevant.
