### ISSUE TITLE
Pohatu Stone Elemental Koli Ball Stuck Bug

### ISSUE THREAD

**Issue by mikeyisroc** [TheLegendOfMataNui/game-issues#263]
**Build Version:**

v1.0.0 REBUILT

**Steps to Reproduce:**

Get stunned by the Stone Elemental and allow it to throw stones. Koli balls that would spawn from stones are  spawned in the monsters face.
[Video](https://www.youtube.com/watch?v=-yheuAbRDsM&feature=youtu.be)

**Comment by ReeseWB-001** [comment]
Duplicate issue of #260 . Please read the full list of issues before submitting a bug report.
