### ISSUE TITLE
Softlock after Tahu's makuta level

### ISSUE THREAD

**Issue by trombone97** [TheLegendOfMataNui/game-issues#266]
**Build Version:**
1.0.0 Rebuilt

**Steps to Reproduce:**
After completing Tahu's portion of level 7, the game crashed after the loading bar filled. Now whenever I load the game it goes to Onua's portion again but I'm tahu with only the pakari, no health or energy, no grappling hook, and no timer.

**Comment by trombone97** [comment]
![1](https://user-images.githubusercontent.com/54301128/63330576-aa38b880-c2f9-11e9-91be-d0b030a7840b.png)
crash screenshot for reference

**Comment by OndrikB** [comment]
That room is currently the end for Makuta's level.

**Comment by ReeseWB-001** [comment]
This issue has been resolved as of 1.4/1.0.1. Exiting Tahu's section now brings you back to the title screen.
