### ISSUE TITLE
Onua Level Crash when entering Elemental caves after collapsing grapple tool platforms

### ISSUE THREAD

**Issue by Mekh4ne** [TheLegendOfMataNui/game-issues#270]
Build:
Rebuilt v1.0.0

After hopping up the platforms and then down the bigger ones, the game crashes after walking around for a bit. I cant seem to find what triggers it. It can occur while entering the next room as well, which results in a corrupted save file and the game crashing at the main menu after hitting "Play game".

Unhandled exception: c0000005
At address: 004de336

**Comment by ReeseWB-001** [comment]
That would be the >100 token crash. This has been fixed as of 1.4/1.0.1.
