### ISSUE TITLE
In the launcher I click The Rebuilt version but it runs the beta

### ISSUE THREAD

**Issue by Jimmylol74** [TheLegendOfMataNui/game-issues#272]
I thought that the version I was playing was the rebuilt, but upon reading some info, I discovered that it was in fact the Beta (the small onua folk doesn´t appear in the beach and the level design is a bit different), What could be wrong? how do I do to play the Rebuilt version?

Thank you in advance!

**Comment by ShadowOfNight** [comment]
Are you still having this problem?

**Comment by LennyTheBionicleLover** [comment]
Have you tried clicking the Rebuilt Installer in BioMedia Project? That’s what I did.

**Comment by Vahkiti** [comment]
Closing this since the OP has not responded in over a year. Will reopen if still relevant.
