### ISSUE TITLE
Kopaka's Makuta level has a switch that is unreachable.

### ISSUE THREAD

**Issue by JeruTz** [TheLegendOfMataNui/game-issues#276]
**Build Version:**

"Beta" October 23, 2001
Rebuilt Patch

**Steps to Reproduce:**

I only just tried out the most recent patch for the first time, but was unable to proceed further than Kopaka's Makuta stage. When triggering the switches to raise the circular platform, the 4th switch that's on the platform itself doesn't rise with the platform when triggering the 2nd and 3rd switches, instead hovering in the void below the platform.

I did find a video of the way the level is supposed to play out, and noticed that when I played it the platform itself was not visible from a distance, while the video had it constantly visible. Could this be a distance fog related issue?

**Comment by ShadowOfNight** [comment]
Rendering distance was in play here for some stuff not showing up in certain parts of the room.  Not to mention the button code itself was pretty borked.  That's all fixed now, marking as resolved.
