### ISSUE TITLE
Game Crash when using grapple in Ga-koro while swimming

### ISSUE THREAD

**Issue by Sven2Win** [TheLegendOfMataNui/game-issues#277]
**Build Version:**
 "Beta" October 23, 2001

**Steps to Reproduce:**
Jump in water deep enough to swim, use grapple.

Unhandled exception: c0000005
at address 6b5297a7

Hope I've submitted this right and haven't missed anything?

**Comment by ReeseWB-001** [comment]
Duplicate issue of #51 .
