### ISSUE TITLE
LOMNTool converts identical DAEs to Xs with varied vertex counts

### ISSUE THREAD

**Issue by Vahkiti** [TheLegendOfMataNui/game-issues#279]
**Expected result:** Models that are topologically identical should output the same vertex count despite mesh position changes.

**Actual result:** Some models output to X with a discrepency of +2-3 vertices. This only affects DAE imports and not OBJ.

**Steps to reproduce:** Convert the attached models to X. The last two will have a vertex count differing from the first two.

https://drive.google.com/open?id=136-_UFgxD-QVv8b-o_T1w8e9SgIcYzWt

Note: This may or may not be related to existing issues regarding vertex duplication, and the resulting workaround of merging them on import. Needs further research to confirm.

**Comment by epicabsol** [comment]
Cannot reproduce. All 4 resulting X files have the same vertex count.

![image](https://user-images.githubusercontent.com/4462127/80318922-518fb880-87c2-11ea-9530-2b509c2139b3.png)
