### ISSUE TITLE
Inventory crashes game

### ISSUE THREAD

**Issue by fedorastories** [TheLegendOfMataNui/game-issues#280]
**Remember to add the following information:**

**Build Version:**

Rebuild

**Steps to Reproduce:**

It's random. I've only made it through Onua's level, but accessing the inventory often crashes the game.

**Comment by ReeseWB-001** [comment]
What's the crash address?

**Comment by LennyTheBionicleLover** [comment]
I have that problem, too. It happened when I was playing Onua in Onu-Koro, I was checking my Inventory, but then it froze, and I couldn’t move. :(

**Comment by LennyTheBionicleLover** [comment]
Same happened with Pohatu’s level. :(

**Comment by ReeseWB-001** [comment]
Duplicate of #49 .
