### ISSUE TITLE
The slowness of the village cutscenes with Matoran

### ISSUE THREAD

**Issue by LennyTheBionicleLover** [TheLegendOfMataNui/game-issues#281]
Build: 

Rebuilt 

Information: 

After I defeated the Rahi in the villages and then talked to the Turaga, when I left the Turaga’s hut, things are a bit slow in terms of movement when there are the Matoran on the villages. Plus, when I do the Takara dances, the animation is slow while the music is not. That’s weird. I am using a 7-year-old Windows 8 laptop HP computer.

**Comment by ReeseWB-001** [comment]
Could you get a video of the issue?

**Comment by Vahkiti** [comment]
Makring as resolved since the OP has not responded in nearly a year. Will reopen if it is still relevant.
