### ISSUE TITLE
The black background does not render behind text when playing in widescreen

### ISSUE THREAD

**Issue by LennyTheBionicleLover** [TheLegendOfMataNui/game-issues#285]
Build: 
Rebuilt. 

Information: 
In Rebuilt, whenever I read the signs or talk to people, there isn’t that black rectangle surrounding the text anymore. Is that a problem?

**Comment by Vahkiti** [comment]
This is known, but due to how much screen space the black bar would take up in widescreen, it's not something we intend to fix.
