### ISSUE TITLE
Game breaks the savefiles.

### ISSUE THREAD

**Issue by darthqba** [TheLegendOfMataNui/game-issues#286]
**Build Version: Rebuild

I was playing about two times and every time my save broke (first in dark level with Onua, second with dark underwater level with Gali). Percentage progress is: 4294967281% !

Bonus: after playing the second save (because first was broken), that second have crashed but first save magically repaired itself. Whats going on?

I played with every option maxed out on fullscreen FHD.

**Comment by ReeseWB-001** [comment]
Issue fixed in version 1.1.
