### ISSUE TITLE
Problem with save file

### ISSUE THREAD

**Issue by Sam-the-Starman** [TheLegendOfMataNui/game-issues#289]
**Build Version:**
Rebuilt

**Information:**
I had just gotten Onua's earthquake ability, but i couldn't figure out which key i had to press to use it, so i closed the game and looked in the game's files hoping to find a file that lists all the controls (i wasn't able to find one). Later once i reloaded the game and got to the save file menu, it said my progress was at 0%. I loaded the save file, i was back at the beach, and i had lost all the health/energy upgrades i had before. At first i thought my save file had been completely reset, but once i got to the village, all the NPCs had the same dialogue as before, and all the sidequests were still complete. Fortunately the portal to the area before the earth elemental was still active as well, so i used that and fought the boss, which caused the game to crash the first time i defeated it (i fought it a second time and the game didnt crash), but that's a separate issue.

**Comment by Vahkiti** [comment]
Fixed as of Beta 1.4.1 and REBUILT 1.0.2.
