### ISSUE TITLE
Re-entering the area of the Takara stage in Ga-Koro will result in a softlock

### ISSUE THREAD

**Issue by 2Tie** [TheLegendOfMataNui/game-issues#29]
if you get too close to the ampitheatre in ga-koro after learning Gali's Dance, it'll warp you back into the cutscene room (MOSH). upon leaving it, it'll place you inside the ampitheatre in VLLG, surrounded by the load trigger for the MOSH room, effectively trapping you if you don't have access to the debug menu.

**Comment by ShadowOfNight** [comment]
@FinalOmega12 Adjusted the position of the spawn point upon exiting the Mosh so the softlock is avoided.  This will have to suffice until we can add in a function to disable the mosh triggers after one use.  Basically so the area can only be visited once for the dance cutscene as going back to there is pointless considering the Mosh is part of the village anyway.

I will leave this issue open until this is fully resolved.

**Comment by ShadowOfNight** [comment]
This is an alpha issue, so this will be closed.
