### ISSUE TITLE
Unhandled Exception: c0000005 At address: 0052e5d9 at launch [Rebuilt]

### ISSUE THREAD

**Issue by frederick-fp** [TheLegendOfMataNui/game-issues#291]
Using Rebuilt v.1.0.2

At boot, via Launcher and simply via the application, the game immediately opens a white screen with Unhandled Exception: c0000005 At address: 0052e5d9. I have attempted to resolve this with both launching with Windows XP (Service Pack 3 & 2) Compatibility, and as administrator, and cleared the Cinematics folder, with no luck.

Regards,
Freddie

**Comment by Vahkiti** [comment]
Your antivirus is most likely flagging one or more of the files in the mods folder. Make sure that's not happening and the issue should be resolved.

**Comment by frederick-fp** [comment]
I ran a scan on the Mods folder, to no success unfortunately.

**Comment by Vahkiti** [comment]
That's not what I meant. I meant for you to confirm that all the files that are supposed to be there are present.

**Comment by fhuewhd** [comment]
I'm getting the same errors at launch some of the time.  Oddly, it did work several times before (at least, the game played, though I'm not sure there weren't bugs somewhere).  But just now it's the white screen and a scattering of "Unhandled exception c000000[last digit runs off end of box]" every time.  

I'm using the "Rebuilt" version, version 1.0.1 if "versionop.txt" is accurate.

I'm running it on Linux via PlayOnLinux, and haven't got an antivirus running.

The files in the "mods" folder are FramerateLimiter.dll, OptionalPatchNative.dll, BetterSaver.dll, BetterBink.dll and OSIProject.DebugServer.dll.  I don't know whether that's what they should be or not.
