### ISSUE TITLE
Launching the grappling hook before a cutscene starts will cause the Toa to disappear after some time 

### ISSUE THREAD

**Issue by OndrikB** [TheLegendOfMataNui/game-issues#292]
**Build Version:**

"Beta" October 23, 2001 (Rebuilt)

**Steps to Reproduce:**

Unlock a dance cutscene
Get the grappling hook (by debug menu or normally, doesn't matter)
Talk to the matoran and, before jumping into the dance pit, fire the grapple at a point where it would bounce off. 

Investigation with the Insert menu shows that the Toa isn't physically moved anywhere, and instead their model simply stops being rendered for some reason.

**Comment by ShadowOfNight** [comment]
Fixed in Rebuilt 1.1
