### ISSUE TITLE
Background pause function can also unpause.

### ISSUE THREAD

**Issue by JeruTz** [TheLegendOfMataNui/game-issues#293]
**Build Version:**

"Beta" October 23, 2001 (Rebuilt)

**Steps to Reproduce:**

This occurs in the rebuilt patch, but likely applies to other versions as well.

Normally, if the game window isn't active, the game automatically pauses all actions. However, if the in game pause menu is open or if either options or inventory are open, the gameplay only remains paused if the window is active. If the user switches to another window at this time, the pause menu remains open, but gameplay action resumes, allowing enemies to attack while the game is paused.

**Comment by LennyTheBionicleLover** [comment]
That’s my problem, too.

**Comment by ShadowOfNight** [comment]
This is a known issue and will be fixed in the next patch.  

Previously reported here: https://github.com/TheLegendOfMataNui/game-issues/issues/133
