### ISSUE TITLE
Fullscreen doesn't work

### ISSUE THREAD

**Issue by ghost** [TheLegendOfMataNui/game-issues#295]
When I'm playing the beta, it doesn't want to be fullscreen, it's always windowed. I'm playing with 1366x768 (16:9) resolution.

**Build Version:**

Beta

**Steps to Reproduce:**

Play with 1366x768 (16:9) resolution
Play the Beta version

This is as close I can get

**Comment by ShadowOfNight** [comment]
As this was discussed and solved in our Discord server (Alt+enter to swap to fullscreen), I'm closing this ticket.
