### ISSUE TITLE
Onu-Koro Crash

### ISSUE THREAD

**Issue by ChargeJN** [TheLegendOfMataNui/game-issues#297]
**Build Version:** Rebuilt

**Steps to Reproduce:**

Near the start of the game, after retrieving the grappling hook as Onua and returning to Onu-Koro, run around a bit and eventually the game will crash.

A window will pop up showing the following.
Unhandled exception: c0000005
At address 005c7d66

**Comment by ShadowOfNight** [comment]
@ChargeJN does this still occur for you as of the latest build?  (v1.1)

This was released after you made this issue, so I'm wondering if this went away or still persists.

**Comment by ShadowOfNight** [comment]
As there has been no reply and this cannot be reproduced currently, closing this issue.
