### ISSUE TITLE
gali level is unplayable

### ISSUE THREAD

**Issue by Joshtheninga** [TheLegendOfMataNui/game-issues#302]
rebuilt 1.1.0
**Steps to Reproduce:**

Give steps to reproduce here.
when i entered the gali level the arrow dosent appear

**Comment by TehSpidah** [comment]
Did you defeat the two fish things and their underwater nests too?

**Comment by Joshtheninga** [comment]
i destroyed all of the nests and its still unplayable

**Comment by ShadowOfNight** [comment]
@Joshtheninga There are currently 4 hives and 4 rahi respectively in Ga-Koro, 2 of each are underwater.  It sounds as though you haven't freed all of them/destroyed all the hives.

**Comment by Joshtheninga** [comment]
Thanks

**Comment by Joshtheninga** [comment]
thanks
