### ISSUE TITLE
part of level 2 gali is unplayable

### ISSUE THREAD

**Issue by Joshtheninga** [TheLegendOfMataNui/game-issues#304]
**Remember to add the following information:**

**1.1.0:**

Rebuilt
**Steps to Reproduce:**
platform doesn't appear when i walk torwards it

**Comment by FuckYouForMakingMeMakeAnAccount** [comment]
Which platform? The one in the area where you get the Rau?

**Comment by Joshtheninga** [comment]
yea

**Comment by FuckYouForMakingMeMakeAnAccount** [comment]
Did you save the village? There's two shark spawners in the sea that you've got to take out and then the platforms should come out to get the Rau.

I don't blame you for missing it because I did exactly the same.

**Comment by Joshtheninga** [comment]
yes but the platforms wont come out

**Comment by ShadowOfNight** [comment]
@Joshtheninga @FuckYouForMakingMeMakeAnAccount 
This is a known issue that has been fixed as part of the next upcoming patch.  Closing this issue.
