### ISSUE TITLE
Warps between ISLD and SHRN are misplaced

### ISSUE THREAD

**Issue by 2Tie** [TheLegendOfMataNui/game-issues#34]
The tunnel in the ravine next to the mountain near the ISLD default spawn is able to be fully swam through without being warped anywhere; Going backwards from SHRN's default spawn places you far below the mountain in ISLD. It's possible that the tunnel to SHRN previously went far lower, but was the warps weren't updated when the tunnel was shortened.

**Comment by ShadowOfNight** [comment]
By adjusting the str2 x,y,z positions I was able to fix the trigger point.  Therefore I'm closing this issue.
