### ISSUE TITLE
Kopaka's WELL area causes a shutdown on entry

### ISSUE THREAD

**Issue by Vahkiti** [TheLegendOfMataNui/game-issues#35]
Either entering the area from the shrine or warping causes a shut down. Curiously, it loads just fine when warped to with any Toa EXCEPT Kopaka.

**Comment by ShadowOfNight** [comment]
Whatever this was has been resolved in the beta.  Closing this issue.

**Comment by Vahkiti** [comment]
Issue to be resolved in the next patch.
