### ISSUE TITLE
Various entities and Toa share animations for different actions

### ISSUE THREAD

**Issue by Vahkiti** [TheLegendOfMataNui/game-issues#36]
Such actions include:
Whenua's idle/talk
Pohatu's and Lewa's  backstep/run.

**Comment by ShadowOfNight** [comment]
Kopaka's and Tahu's backsteps were fixed by @HexadecimalMantis0e.

**Comment by ShadowOfNight** [comment]
All of this appears to have been fixed in the beta, so this is being closed.
