### ISSUE TITLE
Re-entering Tahu's MOSH after the cutscene results in a shutdown

### ISSUE THREAD

**Issue by Vahkiti** [TheLegendOfMataNui/game-issues#38]

**Comment by ShadowOfNight** [comment]
The Mosh was removed and replaced with Vakama's hutt, so this issue is being closed.

**Comment by ShadowOfNight** [comment]
Upon porting this area over to the beta, it was discovered that the Takara for Tahu actually will play.  Unfortunately, reentering afterwards still causes a shut down, so I'm going to reopen the issue.

**Comment by ShadowOfNight** [comment]
The MOSH area has unneeded extra data and is also missing a few lines, which causes the shutdown upon reentry as it doesn't know what to do since the cutscene already played.  Case closed.
