### ISSUE TITLE
Frontend menu options either are not coded, or are currently non-functional

### ISSUE THREAD

**Issue by Vahkiti** [TheLegendOfMataNui/game-issues#42]

**Comment by benf516** [comment]
I am using the beta build with the most recent update, and I cannot get the Front End Menu to function. I may just not know how to control it but I cannot get my mouse to show up, and no button on my keyboard appears to get a response. I am using Windows 10 with the latest updates. I am using an nvidia GTX 1070 and the only setting I have changed was setting it to windowed in the DGVoodoo configuration window.

**Comment by ShadowOfNight** [comment]
Due to this being an unfinished feature in the alpha build rather than a bug, we will not be working on this issue.  Ticket closed.
