### ISSUE TITLE
Quitting out from a boss stage, then loading a new level will not unload the boss. 

### ISSUE THREAD

**Issue by Vahkiti** [TheLegendOfMataNui/game-issues#47]
This issue is most easily noticed when going to Gali's Hydra boss, quitting, and then proceeding approximately halfway through Pohatu's level where the boss will eventually block your path forward. In this case, and possibly others, it results in a softlock.

**Comment by ShadowOfNight** [comment]
This is no longer an issue in the beta, therefore I am closing this.
