### ISSUE TITLE
Collecting the Kanohi Matatu in Kopaka's level will result in a cutscene softlock

### ISSUE THREAD

**Issue by Vahkiti** [TheLegendOfMataNui/game-issues#48]
The cutscene to show what the mask is supposed to do will play indefinitely, with the only method to break it being use of the debug camera.

**Comment by ShadowOfNight** [comment]
Based on what @HexadecimalMantis0e did with the cam.slb file here, it seems this is a problem with the cutscene triggers in the osi.

**Comment by ShadowOfNight** [comment]
This was removed completely in the beta, therefore I'm closing this issue.

**Comment by ShadowOfNight** [comment]
Dummied out the cutscene trigger in the osi to bypass the problem.  Closing issue for now.
