### ISSUE TITLE
Using Gali's grapple claw in water is horribly broken

### ISSUE THREAD

**Issue by Vahkiti** [TheLegendOfMataNui/game-issues#51]

**Comment by ShadowOfNight** [comment]
As the grappling claw was disabled for swimming in the beta, this is no longer a problem.
I am closing this issue.

**Comment by ReeseWB-001** [comment]
Both versions: Causes Gali to be warped far out of bounds, killing her over and over.
Alpha: On respawn, causes a death loop until the area is reloaded.
Beta: Deaths cause particle crash.

**Comment by Vahkiti** [comment]
Closing this and simply using #287 as our thread for this from here on out.
