### ISSUE TITLE
KUTA spawns the player outside the map

### ISSUE THREAD

**Issue by Vahkiti** [TheLegendOfMataNui/game-issues#57]

**Comment by ShadowOfNight** [comment]
The position values in the pos.slb are read in a different order than normal here for some reason.  X, Z, Y is what the order is.  Only issue is the X axis seems to be an inverse, with positive values coming out negative, and vice versa.  Additionally, the spawn is usually in an inverted direction from normal.  More research is needed, but I'm closing this issue for now.
