### ISSUE TITLE
Puzzle cave crash

### ISSUE THREAD

**Issue by ShadowOfNight** [TheLegendOfMataNui/game-issues#6]
In Onua's level, entering the cave to the left of Kapura will cause the game to load the area then crash.  This is defined as PZZL in the debug menu's Warp to Area sub-menu.  The area where Kapura can be found is ATRM.
NOTE: This is one of the areas that puts a saved game into a crash loop.

Update: area is missing a Bcls folder and the Main.ocl file usually contained by those folders.

**Comment by Vahkiti** [comment]
Issue closed: Will be resolved in patch v0.007.
