### ISSUE TITLE
None of the Turaga sans Whenua have programmed conversations

### ISSUE THREAD

**Issue by Vahkiti** [TheLegendOfMataNui/game-issues#60]
Depending on the level, (Gali in particular) this results in a softlock since dialog is required to trigger an event.

**Comment by PeabodySam** [comment]
Whenua should have a conversation after defeating the Vatuka-Nui, but the conversation does not trigger in-game.  The text is present in Lev1_eng.slb:

"The village of Onu-Koro is in your debt, Great Onua. / You have driven many Rahi from our mines / Found several Masks of Power / and defeated the Earth Elemental that blocked the way to the water village of Ga-Koro! / Please take this Makoki Stone as a reward for your efforts. / There are five more Makoki Stones hidden on Mata Nui, but they can only be found by the other Toa. / Your work here is done, Onua. Go seek the other Toa and put an end to the Makuta and his dark schemes!"

**Comment by ShadowOfNight** [comment]
This was completely remedied in the beta, although I had to edit conversation slbs to get all the turaga minus Whenua to use their conversations correctly.  Issue is being closed.

**Comment by ShadowOfNight** [comment]
This was partially an issue in the beta as well, but I'm reopening this since this can be dealt with in the alpha now.

**Comment by ReeseWB-001** [comment]
For clarification, the softlock involved in this seems to currently only pertain to Onewa, as when Pohatu's SHRN's doors actually appear, they won't open. May work when he's given a conversation.

**Comment by robot5431** [comment]
BOSS and HUT dialogue complete and implemented (though it's hard to see most of the BOSS convos due to #40 ). Closing this issue and making a separate one for Onewa's convo not opening the door to GLY1.

**Comment by ReeseWB-001** [comment]
Closing this since the Turaga will be without dialogue for preservation purposes, and the SHRN3 doors are a separate issue. The initial post about Nokama is now known not to be the case, as the Rau event is simply not programmed properly and has nothing to do with a conversation.
