### ISSUE TITLE
Kapura lacks a conversation in Le-Wahi

### ISSUE THREAD

**Issue by Vahkiti** [TheLegendOfMataNui/game-issues#61]

**Comment by ShadowOfNight** [comment]
This was fixed in the beta; issue closed.

**Comment by ReeseWB-001** [comment]
Fixed by backporting the beta's le01_CONV.slb into the alpha's lev5 conversations folder. The Kapura conversation is already present in the lev5_eng.slb, so the only thing missing was the conversation slb.
