### ISSUE TITLE
SCRP crashes during loading

### ISSUE THREAD

**Issue by PeabodySam** [TheLegendOfMataNui/game-issues#68]
The following causes SCRP to load properly:
- Warping to CLF1, then going to SCRP without warping (i.e. passing through CLF2 along the way)
- Warping to SCRP

The following causes SCRP to crash during the loading screen:
- Playing Onua's level normally (i.e. starting at BECH, then going to SCRP without warping)
- Warping to a room prior to CLF1 (e.g. L1A3), then going to SCRP without warping
- Warping to CLF2, then going to SCRP without warping
- Warping to a room after CLF2 (e.g. SPCV), then going to SCRP without warping

The following may or may not cause SCRP to crash:
- Loading SCRP correctly (through either of the first two methods), then exiting the room (going to CLF2) and attempting to re-enter

I have not tested warping to every room in the game, but of the ones I've tried, CLF1 is the only one that nearly consistently allows SCRP to load properly.  I'm not sure why this is.

This seems to be a new issue caused by one of the patches, since the original unpatched game has SCRP load just fine with a normal playthrough of Onua's level (as seen in the Beaverhouse streams).

**Comment by robot5431** [comment]
I've tried the non-crash methods, but it's still crashing for me.

**Comment by PeabodySam** [comment]
Okay... I just tried the CLF1 method three times, and it doesn't seem to be working anymore.  That's really odd.  I swear, it was working consistently when I submitted this issue yesterday.  How could it just stop working like that, without changing anything about the game?

Warping to SCRP still works for me.  At least, for now.  But this new development really puzzles me.

**Comment by Vahkiti** [comment]
IIRC this is a Windows 10 exclusive issue with the Main.x model that will be fixed in the next patch.

**Comment by PeabodySam** [comment]
Err, one minor problem with that resolution... I'm running this game on Windows 7, not Windows 10.

**Comment by robot5431** [comment]
I'm using Windows 8.

**Comment by robot5431** [comment]
Working fine with Patch v0.007.

**Comment by PeabodySam** [comment]
Same here.
