### ISSUE TITLE
GLY3 closed doors do not render

### ISSUE THREAD

**Issue by PeabodySam** [TheLegendOfMataNui/game-issues#69]
In GLY3 of Gali's level, the Whirlpool Glyph is locked behind large golden doors, with Gali needing to push every button in the room in order to open the doors.  However, the doors do not render while they are closed, with a pair of invisible walls being the only thing that blocks players from prematurely collecting the glyph.  When all the buttons have been pushed and the doors are open, then they do render properly.

**Comment by ShadowOfNight** [comment]
@PeabodySam The doors are there and they do render.  But not when you're swimming: 
![lego bionicle_2018_03_12_18_54_08_650](https://user-images.githubusercontent.com/36479507/37319988-f6d2afa2-2647-11e8-8022-63f320b26de3.png)
![lego bionicle_2018_03_12_18_54_35_005](https://user-images.githubusercontent.com/36479507/37319993-fcb30b4c-2647-11e8-865f-a391c74a9d3d.png)

My theory is this is linked to the animations/textures used while you are swimming.

**Comment by PeabodySam** [comment]
Interesting. So this is probably the same issue as things such as underwater Rahi not appearing with red eyes.

**Comment by ShadowOfNight** [comment]
This was resolved in the beta, so therefore I am closing this issue.

**Comment by ReeseWB-001** [comment]
Fixed by backporting the beta's door models. @ShadowOfNight 's theory about the textures seems to be correct, as the doors render perfectly fine when referencing the beta's different texture.
