### ISSUE TITLE
Whenua does not render during Onua's Takara

### ISSUE THREAD

**Issue by PeabodySam** [TheLegendOfMataNui/game-issues#70]
The fact that all other Turaga are in their respective Takara dances would suggest that this is an error, not a deliberate choice.

**Comment by mavaje** [comment]
I had a similar experience where I couldn't see any of the dancers at all. The only way I found them was by their shadow.

**Comment by FinalOmega12** [comment]
Partially fixed. just need a few tweaks before it's ready to go.
