### ISSUE TITLE
Lewa shrine cutscene spawn softlock

### ISSUE THREAD

**Issue by robot5431** [TheLegendOfMataNui/game-issues#72]
Skipping the cutscene where Lewa rides into the shrine after getting the levitation mask causes Lewa to not spawn properly in the SHRN map and the game softlocks. I've tested it multiple times and it happens every time.

EDIT: Checked, and pausing and quitting is still an option. Using the free cam warp can also free you from it. But this is still an issue, no?

**Comment by ShadowOfNight** [comment]
An interesting comparison is the Matatu softlock in Kopaka's level, which also can be escaped merely by turning the debug camera on and off.

**Comment by robot5431** [comment]
UPDATE
The animation for the cutscene still plays, but displaced. After the animations finish, Lewa spawns properly.
Video example: https://youtu.be/0mEKbHD66Rk

**Comment by robot5431** [comment]
Fixed in the beta.

**Comment by ShadowOfNight** [comment]
Fixed as of Alpha patch v1.2.0
