### ISSUE TITLE
Gali Horn 3 causes a shutdown

### ISSUE THREAD

**Issue by robot5431** [TheLegendOfMataNui/game-issues#73]
Interacting with the third horn from the left on top of the waterfall in Ga-Koro causes the game to shut down. The other three horns do not have this problem.

**Comment by ShadowOfNight** [comment]
This was resolved in the beta, so this is being closed.

**Comment by ShadowOfNight** [comment]
Fixed.  There was a typo in the osi code for this horn which was causing the shutdown.
