### ISSUE TITLE
Matoran with wrong mask/foot colors

### ISSUE THREAD

**Issue by PeabodySam** [TheLegendOfMataNui/game-issues#74]
It seems that, with the exception of Onu-Matoran, each village has some Matoran with the wrong foot and/or mask color, using colors associated with another village instead:
- Ga-Matoran with teal feet or lime masks (Le-Matoran colors)
- Po-Matoran with yellow feet/masks or red masks (Ta-Matoran colors)
- Ko-Matoran with dark blue feet (Ga-Matoran colors)
- Le-Matoran with yellow feet or orange masks (Ta-Matoran colors)
- Ta-Matoran with purple feet or black masks (Onu-Matoran colors)

Note that, while yellow would later be considered a canonical Po-Matoran color... that wouldn't be until 2006/2007, and this game was 2001, so that's probably coincidental.  Black is also a Ta-Matoran color in the "battle for Kini-Nui" cutscene in MNOLG, so it _may_ have been intentional... but seeing as this is a late-game cutscene, black may not yet have been part of the Ta-Matoran color palette during this point of TLOMN's development.

**Comment by ShadowOfNight** [comment]
Also note that the Ga-Koro guard in BMTN has Ta-Matoran coloring but is missing a mask.  Additionally, four matoran (which are apparently collect-able?) in MBCH are missing masks and are textureless.  In Po-Wahi, a matoran in BLR4, PTOS, and GLY1 all show up like the four in MBCH.

**Comment by Vahkiti** [comment]
Issue closed. Likely an intentional thing since colours ere not 100% settled upon in 2001.
