### ISSUE TITLE
Turaga with broken vertex colors

### ISSUE THREAD

**Issue by PeabodySam** [TheLegendOfMataNui/game-issues#76]
- Nokama's trident is a mix of black and green.
- Onewa's mask, hands, and lower legs are a mixture of colors, and his hammer is partially green.
- Nuju's mask, lower legs, and pick are a mixture of colors. Additionally, the bones on his mask appear to be distorted; this is especially noticeable when performing the Takara dance.

For the most part, the remaining Turaga are textured correctly, although Vakama's eyes are pitch-black and this may be a related issue.

**Comment by ShadowOfNight** [comment]
Onewa, Matau, and Vakama all have black eyes.  Onewa's eye texture is also the incorrect color.

**Comment by Vahkiti** [comment]
This is a known issue that can't be fixed until Benji updates LOMNTool to support rigged models, ads bad vertex colours on the models themselves are the root of the issue.

**Comment by Vahkiti** [comment]
Issue resolved with the advent of new tools and functions for LOMNTool. Will be implemented in next patch.
