### ISSUE TITLE
VLLG Le-Matoran near Suva has no dialogue

### ISSUE THREAD

**Issue by PeabodySam** [TheLegendOfMataNui/game-issues#77]

**Comment by ShadowOfNight** [comment]
@Vahkiti We fixed this in the Rebuilt patch, but does this need to be fixed in other two builds?

**Comment by Vahkiti** [comment]
@ShadowOfNight Unless the text is present in the SLBs and it's simply not appearing due to a bug, it does not.

**Comment by ShadowOfNight** [comment]
Then in that case, closing this issue.
