### ISSUE TITLE
Problem with using the Kakama on slopes

### ISSUE THREAD

**Issue by PeabodySam** [TheLegendOfMataNui/game-issues#78]
The Kakama tends to have difficulty with sloped ground, especially when the slope is steep.  Going downhill, the Kakama causes the Toa to skip, i.e. traveling forward horizontally through the air and then falling to the ground.  Going uphill, the Kakama causes the Toa to get caught, i.e. left stuck running in place.

I don't know anything about how the game is programmed, but if I had to guess... the Kakama increases the Toa's horizontal speed to the point where it "breaks" the way that the Toa is meant to interact with slopes.  Going downhill, the horizontal speed is faster than the "speed of gravity" that is supposed to keep the Toa grounded.  Going uphill, the increased horizontal speed causes the game treat the rising slope as a wall, preventing the Toa from going forward.  Of course, this is just a guess, as I said.

**Comment by ShadowOfNight** [comment]
Not an issue in the beta.  Closing this issue.

**Comment by ShadowOfNight** [comment]
Due to this requiring a lot of work with the native code on a build that is merely being supported for preservation purposes, we will not be working on this issue.  Ticket closed.
