### ISSUE TITLE
Maskless Ta-Matoran in Kopaka's Level Under Death Plain

### ISSUE THREAD

**Issue by robot5431** [TheLegendOfMataNui/game-issues#80]
In Kopaka's level (specifically in the map TELE) there is a maskless Ta-Matoran standing on a pillar in the pit in the center of the map. The pillar is below the death plain, so the Matoran cannot be interacted with.

**Comment by robot5431** [comment]
Judging by this piece of concept art:
![concept_art_kopaka_and_nuju_lblma](https://user-images.githubusercontent.com/37253627/38331010-b89b9f82-3817-11e8-807e-11bf06d0d424.jpg)
this Matoran was most likely Nuju (judging by the location in the concept art being very similar to TELE's pit). Most likely, what would've happened after obtaining the mask is a cutscene would play where Kopaka would save Nuju and return his Kanohi to him (provided, of course, this concept was used and not scrapped).

**Comment by ShadowOfNight** [comment]
This matoran was removed from this area in the beta, thus I'm closing this issue.
