### ISSUE TITLE
Turagas Nokama, Nuju, and Vakama spawn in their doorways.

### ISSUE THREAD

**Issue by robot5431** [TheLegendOfMataNui/game-issues#82]
This not only makes it difficult to enter/exit the room, but is notable due to Whenua spawning further into his house where he doesn't block the way.

**Comment by ShadowOfNight** [comment]
This is a known issue with Nokama and was introduced by @FinalOmega12 for the other two by using the char file from her as a base to make the other two render.  

Should be an easy fix.
