### ISSUE TITLE
Entering water as Gali causes a black screen followed by death after patch v0.007

### ISSUE THREAD

**Issue by Vahkiti** [TheLegendOfMataNui/game-issues#84]
Once respawned, this issue also causes doors to stop functioning, and the hitboxes of various objects to disappear. This appears to be directly related to the water animation fix introduced in patch v0.007 by generating a new Textures.slb.

A partial fix/workaround for this is to simply quit to the menu and reload Gali's level, or go through a door without having previously entered water.

**Comment by ShadowOfNight** [comment]
Resolved by repairing a broken pointer in the textures.slb from when Vahkiti generated the slb.
