### ISSUE TITLE
Starting a new game from Frontend disables in engine cutscenes

### ISSUE THREAD

**Issue by Vahkiti** [TheLegendOfMataNui/game-issues#85]

**Comment by robot5431** [comment]
In addition, it disables regular Matoran's masks, colors, and dialogue causing a crash when initiating a conversation (though, not Whenua for some reason, who keeps both his dialogue, mask, _and_ colors ), spawns for enemies like the Nui-Jaga and Fikou-Nui (meaning their spawns are tied to cutscenes), and abilities like Onua's digging or grappling claw.

**Comment by ShadowOfNight** [comment]
This has been fixed for sometime now; not sure why this issue was left open.
