### ISSUE TITLE
MUSICLEGOCinematicambience.wav playing over legocineGaliMeetsPohatu.wav

### ISSUE THREAD

**Issue by PeabodySam** [TheLegendOfMataNui/game-issues#87]
During the cutscene where Gali meets Pohatu, two sound files are playing at once: "MUSICLEGOCinematicambience.wav" and "legocineGaliMeetsPohatu.wav". Because the latter already has music, the former probably should not be playing.

**Comment by ShadowOfNight** [comment]
This was fixed in the beta.  Issue closed.

**Comment by ShadowOfNight** [comment]
Fixed in the alpha.
