### ISSUE TITLE
Upon completing either Onua's or Pohatu's levels, the exits do not work.

### ISSUE THREAD

**Issue by robot5431** [TheLegendOfMataNui/game-issues#91]
These are (currently) the only two levels in the game that have "end points" at the moment. In Pohatu's case this makes a bit more sense, as the cutscene for him meeting Kopaka was never made. However, in Onua's case, there is a cutscene in the game's data of him meeting Gali and transferring his Kanohi masks to her (though only his textures render). It should be theoretically possible, then, to make a transition from Onua's level to Gali's level. Clip: https://www.youtube.com/watch?v=apiGe2DA7BQ&t=58s

**Comment by ShadowOfNight** [comment]
This was fixed in the beta, therefore this issue is being closed.

**Comment by ShadowOfNight** [comment]
Code for the exit was missing entirely.  Fixed; issue closed.
