### ISSUE TITLE
Gali's basic energy ball uses the wrong texture when thrown

### ISSUE THREAD

**Issue by robot5431** [TheLegendOfMataNui/game-issues#95]
When selected, her energy ball appears yellow. When thrown, however, it appears green (like Onua and Lewa's). The other Toa do not have this issue (aside from the already mentioned issue with Lewa and Kopaka's upgraded energy balls).

**Comment by robot5431** [comment]
In the beta, this is different but still present. The pickup and icon are yellow, but the laser shots are blue. This applies to Tahu as well, as he uses Onua's laser graphic.

**Comment by ShadowOfNight** [comment]
Changed gali's blue elemental shere textures to yellow to match her eye color.
![image](https://user-images.githubusercontent.com/36479507/40022867-3468e964-5797-11e8-8af0-c55fdd51870f.png)
Edit: Later changed slightly by Vahkiti

**Comment by ShadowOfNight** [comment]
Corrected this in the alpha as well.  OSI was pointing to the wrong textures.
