### ISSUE TITLE
Misaligned forward/backward movement after strafing

### ISSUE THREAD

**Issue by PeabodySam** [TheLegendOfMataNui/game-issues#96]
This one is difficult to describe, but I'll try my best.

If the player strafes left or right and then stops moving, proceeding to move forward or backward will start off with the Toa "misaligned".  Instead of immediately running forward/backward from their current position, the Toa will jerk slightly in the direction that they were strafing (left or right) before moving forward/backward, as though they were "aligning" themselves.

This can make precise movements trickier than they should be, since the player has to account for the initial "misalignment" that has to be corrected once the Toa starts moving.

**Comment by ShadowOfNight** [comment]
Due to this requiring a lot of work with the native code on a build that is merely being supported for preservation purposes, we will not be working on this issue. Ticket closed.
