### ISSUE TITLE
Ice Elemental attack crashes to desktop

### ISSUE THREAD

**Issue by PeabodySam** [TheLegendOfMataNui/game-issues#98]
The boss battle against the Ice Elemental rarely lasts more than a few seconds because, as soon as the Ice Elemental raises its fist to attack, the game immediately crashes to the desktop.  No "unhandled exception" error message pops up.

A possible cause might be the game referencing a sound file that doesn't exist, since that's the only other thing I can think of that causes the game to crash in this manner.  Of course, this is just speculation on my part.

**Comment by ShadowOfNight** [comment]
Whatever it was was fixed in the beta, so this issue is being closed.

**Comment by ShadowOfNight** [comment]
The game script was calling a function that probably shouldn't have been referenced, which was causing a shutdown.  Issue has been resolved.
