### ISSUE TITLE
Onu-Matoran dialogue is present in Lev1_eng.slb, but not displayed in-game

### ISSUE THREAD

**Issue by PeabodySam** [TheLegendOfMataNui/game-issues#99]
![image](https://user-images.githubusercontent.com/36681899/37869577-32d6e238-2f90-11e8-87df-77f3c84eb690.png)

The Onu-Matoran who owns Thali-Whali has a different set of dialogue if you speak to him after returning his pet.  One of these dialogue options is a two-part conversation, with the first part being "Some of the villagers in Onu-Koro are experts in the Dance of Onua."  The second part, as shown above, is incorrectly displayed as "xxx", the placeholder for missing text.

However, the second part _is_ present in Lev1_eng.slb (confirmed to be the correct dialogue for this conversation, based upon the Deep Brick beta): "They may teach you if you could find them."  For some reason, the game doesn't seem to recognize that this is the text for the conversation, instead leading to it displaying "xxx".

**Comment by ShadowOfNight** [comment]
This is likely a conversation slb issue based on my experience working with these.  It was fixed in the beta so I'm closing this issue.

**Comment by ShadowOfNight** [comment]
Conversation slb wasn't the issue ironically, it was the stringtable.  Merged the text groups together and it works correctly now.  Issue closed.
